"""ReAct models - ReAct error handling models.

Defines data models used in the ReAct error handling flow:
- ReActThought: Error analysis and root cause identification
- ReActAction: Action decision (RETRY/CLARIFY/ABORT)
- ReActObservation: Observation result from tool execution
- ReActOutput: Complete output (thought + action)

Design principles (from appendix-e-prompt-model-guide.md):
- Prompt teaches LLM HOW to think (4-section structure)
- Schema tells LLM WHAT to output (XML tags in Field descriptions)
- Field descriptions use XML tags to guide LLM output format

Key Design:
- RETRY can go back to any step (step1, step2, map_fields, build_query)
- LLM analyzes error root cause and decides which step to retry
- All user-facing messages are generated by LLM (in Chinese)
"""

from typing import Any, Dict, List, Literal, Optional
from enum import Enum
from pydantic import BaseModel, ConfigDict, Field


class ReActActionType(str, Enum):
    """ReAct action types."""
    RETRY = "retry"      # Go back to a specific step and retry
    CLARIFY = "clarify"  # Ask user for clarification
    ABORT = "abort"      # Give up and return message to user


class RetryTarget(str, Enum):
    """Target step to retry from."""
    STEP1 = "step1"              # Retry semantic understanding
    STEP2 = "step2"              # Retry computation reasoning
    MAP_FIELDS = "map_fields"    # Retry field mapping
    BUILD_QUERY = "build_query"  # Retry query building


class ReActThought(BaseModel):
    """ReAct thinking output.
    
    LLM analyzes the error, identifies root cause, and decides what to do.
    """
    model_config = ConfigDict(extra="forbid")
    
    error_analysis: str = Field(
        description="""<error_analysis>
Detailed analysis of what went wrong.
Include: error type, error message interpretation, affected components.
</error_analysis>"""
    )
    
    root_cause: str = Field(
        description="""<root_cause>
Identified root cause step: step1 | step2 | map_fields | build_query | execute_query.
Explain WHY this step is the root cause, not just where error occurred.
</root_cause>"""
    )
    
    can_retry: bool = Field(
        description="""<can_retry>
true if error can be fixed by retrying from an earlier step.
false if error is due to data/permission issues or missing information.
</can_retry>"""
    )
    
    needs_clarification: bool = Field(
        description="""<needs_clarification>
true if user clarification is needed (ambiguous field, unclear intent).
false if error can be resolved without user input.
</needs_clarification>"""
    )
    
    reasoning: str = Field(
        description="""<reasoning>
Step-by-step reasoning for the decision.
Include: why this action, why this retry target, what should change.
</reasoning>"""
    )


class ReActAction(BaseModel):
    """ReAct action decision.
    
    Based on thought, decides which action to take.
    """
    model_config = ConfigDict(extra="forbid")
    
    action_type: ReActActionType = Field(
        description="""<action_type>
Action to take: retry | clarify | abort.
- retry: Go back to a specific step with error feedback
- clarify: Ask user for more information
- abort: Give up and explain the issue to user
</action_type>"""
    )
    
    # RETRY: which step to go back to
    retry_from: Optional[RetryTarget] = Field(
        default=None,
        description="""<retry_from>
Required when action_type=retry.
Which step to retry from: step1 | step2 | map_fields | build_query.
Choose the ROOT CAUSE step, not where error occurred.
</retry_from>"""
    )
    
    # RETRY: error feedback to pass to the retry step
    error_feedback: Optional[str] = Field(
        default=None,
        description="""<error_feedback>
Required when action_type=retry. Must be in Chinese.
Feedback to pass to the retry step, including:
- What went wrong (具体错误)
- What should change (修正建议)
- Constraints to consider (约束条件)
</error_feedback>"""
    )
    
    # CLARIFY: question to ask user
    clarification_question: Optional[str] = Field(
        default=None,
        description="""<clarification_question>
Required when action_type=clarify. Must be in Chinese.
Clear question to ask user for clarification.
Be specific about what information is needed.
</clarification_question>"""
    )
    
    # ABORT: user-friendly message
    user_message: Optional[str] = Field(
        default=None,
        description="""<user_message>
Required when action_type=abort. Must be in Chinese.
User-friendly message explaining the issue.
Be helpful: suggest alternatives or explain what user can do.
</user_message>"""
    )


class ReActObservation(BaseModel):
    """ReAct observation result.
    
    Result from tool/step execution, used as input for thought.
    """
    model_config = ConfigDict(extra="forbid")
    
    success: bool = Field(
        description="Whether execution succeeded"
    )
    
    step: str = Field(
        description="Which step produced this observation"
    )
    
    result: Optional[Any] = Field(
        default=None,
        description="Execution result (on success)"
    )
    
    error_type: Optional[str] = Field(
        default=None,
        description="Error type (on failure)"
    )
    
    error_message: Optional[str] = Field(
        default=None,
        description="Error message (on failure)"
    )
    
    error_details: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Additional error details (on failure)"
    )


class ReActOutput(BaseModel):
    """ReAct complete output (single round).
    
    Contains thought and action from LLM.
    """
    model_config = ConfigDict(extra="forbid")
    
    thought: ReActThought = Field(
        description="LLM's analysis of the error"
    )
    
    action: ReActAction = Field(
        description="LLM's decision on what to do"
    )


__all__ = [
    "ReActThought",
    "ReActAction",
    "ReActActionType",
    "ReActObservation",
    "ReActOutput",
    "RetryTarget",
]
