# -*- coding: utf-8 -*-
"""ReAct models - Error handling and recovery models.

Defines data models used in the ReAct error handling flow:
- ReActThought: Error analysis and root cause identification
- ReActAction: Action decision (CORRECT/RETRY/CLARIFY/ABORT)
- Correction: Direct correction to Step1/Step2 output
- ReActOutput: Complete output (thought + action)

Design principles (from prompt_and_models规范文档.md):
- Prompt teaches LLM HOW to think (domain concepts, analysis methods)
- Schema tells LLM WHAT to output (field meanings, fill rules, decision rules)
- Enum selection rules only in Enum docstring <rule> tag

Key Design:
- CORRECT: Directly fix Step1/Step2 output without re-running LLM
- RETRY: Go back to a step with specific guidance
- CLARIFY: Ask user for clarification
- ABORT: Give up and explain to user
- All user-facing messages are generated by LLM (in Chinese)
"""

from typing import Any, Literal
from enum import Enum
from pydantic import BaseModel, ConfigDict, Field


class ReActActionType(str, Enum):
    """React action types.
    
    <rule>
    CORRECT: Can directly fix the output without re-running LLM
      → Duplicate measures, simple field fixes, value corrections
    RETRY: Need LLM to re-think with new guidance
      → Logic errors, computation design issues, missing information
    CLARIFY: Need user input to proceed
      → Ambiguous fields, unclear intent, multiple interpretations
    ABORT: Cannot recover, explain to user
      → Permission denied, data not available, unrecoverable errors
    </rule>
    """
    CORRECT = "correct"
    RETRY = "retry"
    CLARIFY = "clarify"
    ABORT = "abort"


class ErrorCategory(str, Enum):
    """Error category for diagnosis.
    
    <rule>
    DUPLICATE_FIELD: Same field_name appears multiple times in query
      → Usually CORRECT: remove duplicates, keep base measure
    FIELD_NOT_FOUND: Referenced field doesn't exist in data source
      → RETRY map_fields with guidance, or ABORT if field truly doesn't exist
    INVALID_COMPUTATION: Computation logic error (wrong calc_type, missing params)
      → RETRY step2 with specific guidance
    INVALID_AGGREGATION: Aggregation mismatch or invalid aggregation
      → RETRY step1 or step2 with guidance
    TYPE_MISMATCH: Data type incompatibility
      → RETRY step1 or step2 with guidance
    SYNTAX_ERROR: Query syntax error
      → RETRY build_query with guidance
    PERMISSION_DENIED: Access denied to data source
      → ABORT with explanation
    TIMEOUT: Query execution timeout
      → ABORT or suggest simplifying query
    UNKNOWN: Cannot determine error category
      → Analyze further or ABORT
    </rule>
    """
    DUPLICATE_FIELD = "duplicate_field"
    FIELD_NOT_FOUND = "field_not_found"
    INVALID_COMPUTATION = "invalid_computation"
    INVALID_AGGREGATION = "invalid_aggregation"
    TYPE_MISMATCH = "type_mismatch"
    SYNTAX_ERROR = "syntax_error"
    PERMISSION_DENIED = "permission_denied"
    TIMEOUT = "timeout"
    UNKNOWN = "unknown"


class CorrectionOperation(str, Enum):
    """Correction operation types.
    
    <rule>
    REMOVE_DUPLICATE_MEASURES: Remove measures with same field_name, keep only base measure
      → For "Field X isn't unique" errors caused by duplicate measures
    REPLACE_FIELD: Replace a field reference with correct one
      → For field name typos or wrong field references
    REMOVE_FIELD: Remove a field from list
      → For invalid or unnecessary fields
    ADD_FIELD: Add a field to list
      → For missing required fields
    UPDATE_VALUE: Update a specific value
      → For incorrect parameter values
    </rule>
    """
    REMOVE_DUPLICATE_MEASURES = "remove_duplicate_measures"
    REPLACE_FIELD = "replace_field"
    REMOVE_FIELD = "remove_field"
    ADD_FIELD = "add_field"
    UPDATE_VALUE = "update_value"


class Correction(BaseModel):
    """Direct correction to Step1/Step2 output.
    
    <fill_order>
    1. target_step
    2. target_path
    3. operation
    4. reason
    5. corrected_value (if needed)
    </fill_order>
    
    <examples>
    Remove duplicate measures: {"target_step": "step1", "target_path": "what.measures", "operation": "remove_duplicate_measures", "reason": "Sales appears twice"}
    Update partition_by: {"target_step": "step2", "target_path": "computations[0].partition_by", "operation": "update_value", "reason": "Add Category to partition", "corrected_value": [{"field_name": "Category"}]}
    </examples>
    
    <anti_patterns>
    X partition_by with string list like ["Category"] instead of [{"field_name": "Category"}]
    X where.dimensions with string list instead of DimensionField object list
    </anti_patterns>
    """
    model_config = ConfigDict(extra="forbid")
    
    target_step: Literal["step1", "step2"] = Field(
        description="""<what>Which step's output to correct</what>
<when>ALWAYS</when>"""
    )
    
    target_path: str = Field(
        description="""<what>JSON path to the field to correct</what>
<when>ALWAYS</when>"""
    )
    
    operation: CorrectionOperation = Field(
        description="""<what>Type of correction operation</what>
<when>ALWAYS</when>"""
    )
    
    reason: str = Field(
        description="""<what>Why this correction is needed (in Chinese)</what>
<when>ALWAYS</when>"""
    )
    
    corrected_value: Any = Field(
        default=None,
        description="""<what>The corrected value to use</what>
<when>For REPLACE_FIELD, ADD_FIELD, UPDATE_VALUE operations</when>
<dependency>Required when operation needs a new value</dependency>
<must_not>Use string list for partition_by or dimensions - must use object list with field_name key</must_not>"""
    )


class ReActThought(BaseModel):
    """LLM's analysis of the error.
    
    <fill_order>
    1. error_source (which step)
    2. error_category (what type)
    3. root_cause_analysis (why)
    4. can_correct (directly fixable?)
    5. can_retry (worth retrying?)
    6. needs_clarification (need user?)
    7. reasoning (decision explanation)
    </fill_order>
    """
    model_config = ConfigDict(extra="forbid")
    
    error_source: str = Field(
        description="""<what>Which step caused the error</what>
<when>ALWAYS</when>
<values>step1, step2, map_fields, build_query, execute_query</values>"""
    )
    
    error_category: ErrorCategory = Field(
        description="""<what>Category of the error</what>
<when>ALWAYS</when>"""
    )
    
    root_cause_analysis: str = Field(
        description="""<what>Deep analysis of why this error occurred (in Chinese)</what>
<when>ALWAYS</when>
<rule>Explain the root cause, not just describe the error</rule>"""
    )
    
    can_correct: bool = Field(
        description="""<what>Whether error can be fixed by direct correction</what>
<when>ALWAYS</when>
<rule>True if output can be fixed without re-running LLM (e.g., remove duplicates)</rule>"""
    )
    
    can_retry: bool = Field(
        description="""<what>Whether retrying with guidance could fix the error</what>
<when>ALWAYS</when>
<rule>True if LLM re-thinking with new guidance could produce correct output</rule>"""
    )
    
    needs_clarification: bool = Field(
        description="""<what>Whether user clarification is needed</what>
<when>ALWAYS</when>
<rule>True if error is due to ambiguous user input or unclear intent</rule>"""
    )
    
    reasoning: str = Field(
        description="""<what>Step-by-step reasoning for the decision (in Chinese)</what>
<when>ALWAYS</when>"""
    )


class ReActAction(BaseModel):
    """LLM's decision on what to do.
    
    <fill_order>
    1. action_type (ALWAYS)
    2. corrections (if CORRECT)
    3. retry_from, retry_guidance (if RETRY)
    4. clarification_question (if CLARIFY)
    5. user_message (if ABORT)
    </fill_order>
    
    <anti_patterns>
    X action_type=CORRECT but no corrections provided
    X action_type=RETRY but no retry_from or retry_guidance
    X action_type=CLARIFY but no clarification_question
    X action_type=ABORT but no user_message
    </anti_patterns>
    """
    model_config = ConfigDict(extra="forbid")
    
    action_type: ReActActionType = Field(
        description="""<what>Action to take</what>
<when>ALWAYS</when>"""
    )
    
    # CORRECT
    corrections: list[Correction] | None = Field(
        default=None,
        description="""<what>List of corrections to apply</what>
<when>action_type = CORRECT</when>
<dependency>Required for CORRECT action</dependency>"""
    )
    
    # RETRY
    retry_from: str | None = Field(
        default=None,
        description="""<what>Which step to retry from</what>
<when>action_type = RETRY</when>
<values>step1, step2, map_fields, build_query</values>
<dependency>Required for RETRY action</dependency>"""
    )
    
    retry_guidance: str | None = Field(
        default=None,
        description="""<what>Specific guidance for the retry (in Chinese)</what>
<when>action_type = RETRY</when>
<rule>Must be specific and actionable, tell the step exactly what to do differently</rule>
<dependency>Required for RETRY action</dependency>"""
    )
    
    # CLARIFY
    clarification_question: str | None = Field(
        default=None,
        description="""<what>Question to ask user (in Chinese)</what>
<when>action_type = CLARIFY</when>
<rule>Must be clear and specific about what information is needed</rule>
<dependency>Required for CLARIFY action</dependency>"""
    )
    
    # ABORT
    user_message: str | None = Field(
        default=None,
        description="""<what>Message to show user (in Chinese)</what>
<when>action_type = ABORT</when>
<rule>Must be helpful, explain the issue, and suggest alternatives if possible</rule>
<dependency>Required for ABORT action</dependency>"""
    )


class ReActOutput(BaseModel):
    """ReAct complete output (single round).
    
    <fill_order>
    1. thought (analyze error)
    2. action (decide what to do)
    </fill_order>
    """
    model_config = ConfigDict(extra="forbid")
    
    thought: ReActThought = Field(
        description="""<what>LLM's analysis of the error</what>
<when>ALWAYS</when>"""
    )
    
    action: ReActAction = Field(
        description="""<what>LLM's decision on what to do</what>
<when>ALWAYS</when>"""
    )


__all__ = [
    "ReActActionType",
    "ErrorCategory",
    "CorrectionOperation",
    "Correction",
    "ReActThought",
    "ReActAction",
    "ReActOutput",
]
