# -*- coding: utf-8 -*-
"""
Replanner Agent Prompts

Following PROMPT_AND_MODEL_GUIDE.md specification:
- Prompt tells LLM HOW to think (Role, Task, Domain Knowledge, Constraints)
- Schema tells LLM WHAT to output (field definitions, XML tags)
- Use VizQLPrompt base class with 4-section structure
- Output Model auto-injects JSON Schema

Core functionality:
- Evaluate current insight completeness
- Identify missing analysis aspects
- Generate exploration questions based on dimension_hierarchy
- Assign priority to each question

Design Specification: insight-design.md
"""

from typing import Type
from pydantic import BaseModel

from tableau_assistant.src.agents.base.prompt import VizQLPrompt
from tableau_assistant.src.agents.replanner.models import ReplanDecision


class ReplannerPrompt(VizQLPrompt):
    """
    Replanner Agent Prompt - Intelligent Replanning
    
    Design principles:
    - Prompt tells LLM HOW to think (domain knowledge + reasoning steps)
    - Schema tells LLM WHAT to output (field filling rules)
    - Prompt does NOT contain specific field names or keyword mappings
    - Thinking steps correspond to <decision_rule> in Schema
    """
    
    def get_role(self) -> str:
        """
        Define LLM role (activate knowledge subspace)
        
        Target: ~20 words
        """
        return """Data analysis strategist who evaluates insight completeness and orchestrates exploration.

Expertise: completeness assessment, gap identification, exploration planning, question generation, priority assignment"""
    
    def get_task(self) -> str:
        """
        Define task (focus attention)
        
        Target: ~50 words with implicit CoT
        """
        return """Evaluate current insights and decide if more analysis is needed.

Process: Assess completeness → Identify gaps → Select exploration type → Generate questions → Assign priority → Output JSON"""
    
    def get_specific_domain_knowledge(self) -> str:
        """
        Provide domain knowledge and thinking steps (HOW to think)
        
        Note: Does NOT contain specific field names or keyword mappings - those are in Schema's <rule>
        
        Target: ~200 words
        """
        return """**Think step by step:**

Step 1: Assess completeness
- Does the insight directly answer the user's question?
- Are all aspects of the question addressed?
- Is there enough detail to understand "why"?

Step 2: Identify gaps (if not complete)
- What aspects are missing from the analysis?
- Which dimensions have not been explored?
- Are there unexplored relationships or patterns?

Step 3: Check deduplication (CRITICAL)
- Review answered_questions list for similar questions
- "Similar" = same dimension + same analysis type
- Never repeat exact question text

Step 4: Select exploration type based on gap nature
- Need finer granularity? Consider drilling down
- Need broader perspective? Consider rolling up
- Missing temporal patterns? Consider time-based analysis
- Need entity comparison? Consider peer comparison
- Only one dimension analyzed? Consider cross-dimensional analysis
- Found anomalies? Consider investigation
- Need relationship analysis? Consider correlation

Step 5: Generate questions
- Questions generated by YOU directly, NOT from templates
- Use actual entity names from insights
- Each question targets ONE specific dimension from dimension_hierarchy
- Questions in user's language (see user_language parameter)

Step 6: Assign priority
- Higher priority for questions that directly answer user's question
- Lower priority for edge exploration

**Using dimension_hierarchy:**
- Use category and level to determine appropriate exploration direction
- Coarse levels (level=1,2) can drill down to finer levels
- Fine levels (level=3,4) can roll up to coarser levels

**Using data_insight_profile:**
- Use distribution characteristics to guide focus areas
- Anomalies and clusters suggest investigation opportunities"""
    
    def get_constraints(self) -> str:
        """
        Define constraints
        
        Target: 3-5 rules, ~10 words each
        """
        return """MUST:
- Generate questions in user's language with actual entity names
- Check answered_questions before generating new questions
- Follow <decision_rule> in Schema for each field
- Use diverse exploration types

MUST NOT:
- Use template placeholders like {entity}
- Generate more than 5 questions per round
- Repeat questions already in answered_questions"""
    
    def get_user_template(self) -> str:
        return """## User Language
{user_language}

## Original Question
{original_question}

## Current Insights
{insights_summary}

## Data Insight Profile (Phase 1 Statistical Analysis)
{data_insight_profile}

## Dimension Hierarchy
{dimension_hierarchy}

## Current Analyzed Dimensions
{current_dimensions}

## Answered Questions (for deduplication)
{answered_questions}

## Replan Round
Current round: {current_round}
Max rounds: {max_rounds}

Analyze the current insights and output ReplanDecision."""
    
    def get_output_model(self) -> Type[BaseModel]:
        return ReplanDecision


# Prompt instance
REPLANNER_PROMPT = ReplannerPrompt()


__all__ = [
    "ReplannerPrompt",
    "REPLANNER_PROMPT",
]
