# -*- coding: utf-8 -*-
"""
维度模式种子数据

预置常见维度模式，覆盖主要类别：
- time: 时间维度（年、季度、月、周、日等）
- geography: 地理维度（国家、省份、城市、区县等）
- product: 产品维度（类别、子类、品牌、SKU 等）
- customer: 客户维度（客户类型、客户名称等）
- organization: 组织维度（部门、团队、员工等）
- channel: 渠道维度（一级渠道、二级渠道等）
- financial: 财务维度（科目、成本中心等）

用于 RAG 检索和 LLM few-shot 示例。
"""
from typing import List, Dict, Any


# ══════════════════════════════════════════════════════════════
# 种子数据定义
# ══════════════════════════════════════════════════════════════

SEED_PATTERNS: List[Dict[str, Any]] = [
    # ─────────────────────────────────────────────────────────
    # TIME 时间维度 - 中文
    # ─────────────────────────────────────────────────────────
    {
        "field_caption": "年",
        "data_type": "integer",
        "category": "time",
        "category_detail": "time-year",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "时间维度最粗粒度，表示年份",
    },
    {
        "field_caption": "年份",
        "data_type": "integer",
        "category": "time",
        "category_detail": "time-year",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "时间维度最粗粒度，表示年份",
    },
    {
        "field_caption": "季度",
        "data_type": "string",
        "category": "time",
        "category_detail": "time-quarter",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "时间维度粗粒度，表示季度",
    },
    {
        "field_caption": "月",
        "data_type": "integer",
        "category": "time",
        "category_detail": "time-month",
        "level": 3,
        "granularity": "medium",
        "reasoning": "时间维度中等粒度，表示月份",
    },
    {
        "field_caption": "月份",
        "data_type": "integer",
        "category": "time",
        "category_detail": "time-month",
        "level": 3,
        "granularity": "medium",
        "reasoning": "时间维度中等粒度，表示月份",
    },
    {
        "field_caption": "周",
        "data_type": "integer",
        "category": "time",
        "category_detail": "time-week",
        "level": 4,
        "granularity": "fine",
        "reasoning": "时间维度细粒度，表示周",
    },
    {
        "field_caption": "日期",
        "data_type": "date",
        "category": "time",
        "category_detail": "time-date",
        "level": 5,
        "granularity": "finest",
        "reasoning": "时间维度最细粒度，表示日期",
    },
    {
        "field_caption": "日",
        "data_type": "integer",
        "category": "time",
        "category_detail": "time-day",
        "level": 5,
        "granularity": "finest",
        "reasoning": "时间维度最细粒度，表示日",
    },
    # ─────────────────────────────────────────────────────────
    # TIME 时间维度 - 英文
    # ─────────────────────────────────────────────────────────
    {
        "field_caption": "year",
        "data_type": "integer",
        "category": "time",
        "category_detail": "time-year",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Time dimension coarsest level, represents year",
    },
    {
        "field_caption": "Year",
        "data_type": "integer",
        "category": "time",
        "category_detail": "time-year",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Time dimension coarsest level, represents year",
    },
    {
        "field_caption": "fiscal_year",
        "data_type": "integer",
        "category": "time",
        "category_detail": "time-year",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Fiscal year, time dimension coarsest level",
    },
    {
        "field_caption": "quarter",
        "data_type": "string",
        "category": "time",
        "category_detail": "time-quarter",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Time dimension coarse level, represents quarter",
    },
    {
        "field_caption": "Quarter",
        "data_type": "string",
        "category": "time",
        "category_detail": "time-quarter",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Time dimension coarse level, represents quarter",
    },
    {
        "field_caption": "month",
        "data_type": "integer",
        "category": "time",
        "category_detail": "time-month",
        "level": 3,
        "granularity": "medium",
        "reasoning": "Time dimension medium level, represents month",
    },
    {
        "field_caption": "Month",
        "data_type": "integer",
        "category": "time",
        "category_detail": "time-month",
        "level": 3,
        "granularity": "medium",
        "reasoning": "Time dimension medium level, represents month",
    },
    {
        "field_caption": "month_name",
        "data_type": "string",
        "category": "time",
        "category_detail": "time-month",
        "level": 3,
        "granularity": "medium",
        "reasoning": "Month name, time dimension medium level",
    },
    {
        "field_caption": "week",
        "data_type": "integer",
        "category": "time",
        "category_detail": "time-week",
        "level": 4,
        "granularity": "fine",
        "reasoning": "Time dimension fine level, represents week",
    },
    {
        "field_caption": "week_number",
        "data_type": "integer",
        "category": "time",
        "category_detail": "time-week",
        "level": 4,
        "granularity": "fine",
        "reasoning": "Week number, time dimension fine level",
    },
    {
        "field_caption": "date",
        "data_type": "date",
        "category": "time",
        "category_detail": "time-date",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Time dimension finest level, represents date",
    },
    {
        "field_caption": "order_date",
        "data_type": "date",
        "category": "time",
        "category_detail": "time-date",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Order date, time dimension finest level",
    },
    {
        "field_caption": "ship_date",
        "data_type": "date",
        "category": "time",
        "category_detail": "time-date",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Ship date, time dimension finest level",
    },
    {
        "field_caption": "create_date",
        "data_type": "date",
        "category": "time",
        "category_detail": "time-date",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Create date, time dimension finest level",
    },
    {
        "field_caption": "day",
        "data_type": "integer",
        "category": "time",
        "category_detail": "time-day",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Day of month, time dimension finest level",
    },
    {
        "field_caption": "day_of_week",
        "data_type": "string",
        "category": "time",
        "category_detail": "time-day",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Day of week, time dimension finest level",
    },

    # ─────────────────────────────────────────────────────────
    # GEOGRAPHY 地理维度 - 中文
    # ─────────────────────────────────────────────────────────
    {
        "field_caption": "国家",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-country",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "地理维度最粗粒度，表示国家",
    },
    {
        "field_caption": "省份",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-province",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "地理维度粗粒度，表示省份",
    },
    {
        "field_caption": "省区",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-province",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "地理维度粗粒度，表示省/区",
    },
    {
        "field_caption": "城市",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-city",
        "level": 3,
        "granularity": "medium",
        "reasoning": "地理维度中等粒度，表示城市",
    },
    {
        "field_caption": "区县",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-district",
        "level": 4,
        "granularity": "fine",
        "reasoning": "地理维度细粒度，表示区县",
    },
    {
        "field_caption": "客户省",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-province",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "客户所在省份，地理维度粗粒度",
    },
    {
        "field_caption": "客户区",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-district",
        "level": 4,
        "granularity": "fine",
        "reasoning": "客户所在区县，地理维度细粒度",
    },
    {
        "field_caption": "地区",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-region",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "地理维度粗粒度，表示地区",
    },
    {
        "field_caption": "大区",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-region",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "地理维度最粗粒度，表示大区",
    },
    # ─────────────────────────────────────────────────────────
    # GEOGRAPHY 地理维度 - 英文
    # ─────────────────────────────────────────────────────────
    {
        "field_caption": "country",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-country",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Geography dimension coarsest level, represents country",
    },
    {
        "field_caption": "Country",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-country",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Geography dimension coarsest level, represents country",
    },
    {
        "field_caption": "country_name",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-country",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Country name, geography dimension coarsest level",
    },
    {
        "field_caption": "region",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-region",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Geography dimension coarse level, represents region",
    },
    {
        "field_caption": "Region",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-region",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Geography dimension coarse level, represents region",
    },
    {
        "field_caption": "state",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-province",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "State/Province, geography dimension coarse level",
    },
    {
        "field_caption": "State",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-province",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "State/Province, geography dimension coarse level",
    },
    {
        "field_caption": "province",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-province",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Province, geography dimension coarse level",
    },
    {
        "field_caption": "city",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-city",
        "level": 3,
        "granularity": "medium",
        "reasoning": "Geography dimension medium level, represents city",
    },
    {
        "field_caption": "City",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-city",
        "level": 3,
        "granularity": "medium",
        "reasoning": "Geography dimension medium level, represents city",
    },
    {
        "field_caption": "city_name",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-city",
        "level": 3,
        "granularity": "medium",
        "reasoning": "City name, geography dimension medium level",
    },
    {
        "field_caption": "district",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-district",
        "level": 4,
        "granularity": "fine",
        "reasoning": "Geography dimension fine level, represents district",
    },
    {
        "field_caption": "postal_code",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-postal",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Postal code, geography dimension finest level",
    },
    {
        "field_caption": "zip_code",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-postal",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Zip code, geography dimension finest level",
    },
    {
        "field_caption": "address",
        "data_type": "string",
        "category": "geography",
        "category_detail": "geography-address",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Address, geography dimension finest level",
    },

    # ─────────────────────────────────────────────────────────
    # PRODUCT 产品维度 - 中文
    # ─────────────────────────────────────────────────────────
    {
        "field_caption": "产品类别",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-category",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "产品维度最粗粒度，表示产品大类",
    },
    {
        "field_caption": "事业线名称",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-business-line",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "产品维度最粗粒度，表示事业线",
    },
    {
        "field_caption": "产品子类",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-subcategory",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "产品维度粗粒度，表示产品子类",
    },
    {
        "field_caption": "品牌",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-brand",
        "level": 3,
        "granularity": "medium",
        "reasoning": "产品维度中等粒度，表示品牌",
    },
    {
        "field_caption": "产品名称",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-name",
        "level": 4,
        "granularity": "fine",
        "reasoning": "产品维度细粒度，表示产品名称",
    },
    {
        "field_caption": "物料名称",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-name",
        "level": 4,
        "granularity": "fine",
        "reasoning": "物料名称，产品维度细粒度",
    },
    {
        "field_caption": "物料编码",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-sku",
        "level": 5,
        "granularity": "finest",
        "reasoning": "物料编码，产品维度最细粒度",
    },
    {
        "field_caption": "SKU",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-sku",
        "level": 5,
        "granularity": "finest",
        "reasoning": "SKU编码，产品维度最细粒度",
    },
    # ─────────────────────────────────────────────────────────
    # PRODUCT 产品维度 - 英文
    # ─────────────────────────────────────────────────────────
    {
        "field_caption": "category",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-category",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Product dimension coarsest level, represents category",
    },
    {
        "field_caption": "Category",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-category",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Product dimension coarsest level, represents category",
    },
    {
        "field_caption": "product_category",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-category",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Product category, product dimension coarsest level",
    },
    {
        "field_caption": "subcategory",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-subcategory",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Product dimension coarse level, represents subcategory",
    },
    {
        "field_caption": "Sub-Category",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-subcategory",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Product dimension coarse level, represents subcategory",
    },
    {
        "field_caption": "product_subcategory",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-subcategory",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Product subcategory, product dimension coarse level",
    },
    {
        "field_caption": "brand",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-brand",
        "level": 3,
        "granularity": "medium",
        "reasoning": "Product dimension medium level, represents brand",
    },
    {
        "field_caption": "Brand",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-brand",
        "level": 3,
        "granularity": "medium",
        "reasoning": "Product dimension medium level, represents brand",
    },
    {
        "field_caption": "brand_name",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-brand",
        "level": 3,
        "granularity": "medium",
        "reasoning": "Brand name, product dimension medium level",
    },
    {
        "field_caption": "product_name",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-name",
        "level": 4,
        "granularity": "fine",
        "reasoning": "Product name, product dimension fine level",
    },
    {
        "field_caption": "Product Name",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-name",
        "level": 4,
        "granularity": "fine",
        "reasoning": "Product name, product dimension fine level",
    },
    {
        "field_caption": "material_name",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-name",
        "level": 4,
        "granularity": "fine",
        "reasoning": "Material name, product dimension fine level",
    },
    {
        "field_caption": "sku",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-sku",
        "level": 5,
        "granularity": "finest",
        "reasoning": "SKU, product dimension finest level",
    },
    {
        "field_caption": "product_id",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-sku",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Product ID, product dimension finest level",
    },
    {
        "field_caption": "Product ID",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-sku",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Product ID, product dimension finest level",
    },
    {
        "field_caption": "material",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-sku",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Material code, product dimension finest level",
    },
    {
        "field_caption": "item_id",
        "data_type": "string",
        "category": "product",
        "category_detail": "product-sku",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Item ID, product dimension finest level",
    },

    # ─────────────────────────────────────────────────────────
    # CUSTOMER 客户维度 - 中文
    # ─────────────────────────────────────────────────────────
    {
        "field_caption": "客户类型",
        "data_type": "string",
        "category": "customer",
        "category_detail": "customer-type",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "客户维度最粗粒度，表示客户类型",
    },
    {
        "field_caption": "客户分类",
        "data_type": "string",
        "category": "customer",
        "category_detail": "customer-segment",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "客户维度粗粒度，表示客户分类",
    },
    {
        "field_caption": "客户名称",
        "data_type": "string",
        "category": "customer",
        "category_detail": "customer-name",
        "level": 3,
        "granularity": "medium",
        "reasoning": "客户维度中等粒度，表示客户名称",
    },
    {
        "field_caption": "客户ID",
        "data_type": "string",
        "category": "customer",
        "category_detail": "customer-id",
        "level": 5,
        "granularity": "finest",
        "reasoning": "客户维度最细粒度，表示客户唯一标识",
    },
    {
        "field_caption": "客户编码",
        "data_type": "string",
        "category": "customer",
        "category_detail": "customer-id",
        "level": 5,
        "granularity": "finest",
        "reasoning": "客户维度最细粒度，表示客户编码",
    },
    # ─────────────────────────────────────────────────────────
    # CUSTOMER 客户维度 - 英文
    # ─────────────────────────────────────────────────────────
    {
        "field_caption": "customer_type",
        "data_type": "string",
        "category": "customer",
        "category_detail": "customer-type",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Customer dimension coarsest level, represents customer type",
    },
    {
        "field_caption": "Customer Type",
        "data_type": "string",
        "category": "customer",
        "category_detail": "customer-type",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Customer dimension coarsest level, represents customer type",
    },
    {
        "field_caption": "segment",
        "data_type": "string",
        "category": "customer",
        "category_detail": "customer-segment",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Customer segment, customer dimension coarse level",
    },
    {
        "field_caption": "Segment",
        "data_type": "string",
        "category": "customer",
        "category_detail": "customer-segment",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Customer segment, customer dimension coarse level",
    },
    {
        "field_caption": "customer_segment",
        "data_type": "string",
        "category": "customer",
        "category_detail": "customer-segment",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Customer segment, customer dimension coarse level",
    },
    {
        "field_caption": "customer_name",
        "data_type": "string",
        "category": "customer",
        "category_detail": "customer-name",
        "level": 3,
        "granularity": "medium",
        "reasoning": "Customer name, customer dimension medium level",
    },
    {
        "field_caption": "Customer Name",
        "data_type": "string",
        "category": "customer",
        "category_detail": "customer-name",
        "level": 3,
        "granularity": "medium",
        "reasoning": "Customer name, customer dimension medium level",
    },
    {
        "field_caption": "customer_id",
        "data_type": "string",
        "category": "customer",
        "category_detail": "customer-id",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Customer ID, customer dimension finest level",
    },
    {
        "field_caption": "Customer ID",
        "data_type": "string",
        "category": "customer",
        "category_detail": "customer-id",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Customer ID, customer dimension finest level",
    },
    {
        "field_caption": "sold_to",
        "data_type": "string",
        "category": "customer",
        "category_detail": "customer-id",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Sold-to party code, customer dimension finest level",
    },
    {
        "field_caption": "ship_to",
        "data_type": "string",
        "category": "customer",
        "category_detail": "customer-id",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Ship-to party code, customer dimension finest level",
    },

    # ─────────────────────────────────────────────────────────
    # ORGANIZATION 组织维度 - 中文
    # ─────────────────────────────────────────────────────────
    {
        "field_caption": "公司名称",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-company",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "组织维度最粗粒度，表示公司",
    },
    {
        "field_caption": "公司",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-company",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "组织维度最粗粒度，表示公司",
    },
    {
        "field_caption": "部门",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-department",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "组织维度粗粒度，表示部门",
    },
    {
        "field_caption": "团队",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-team",
        "level": 3,
        "granularity": "medium",
        "reasoning": "组织维度中等粒度，表示团队",
    },
    {
        "field_caption": "员工",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-employee",
        "level": 5,
        "granularity": "finest",
        "reasoning": "组织维度最细粒度，表示员工",
    },
    {
        "field_caption": "员工姓名",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-employee",
        "level": 5,
        "granularity": "finest",
        "reasoning": "组织维度最细粒度，表示员工姓名",
    },
    {
        "field_caption": "销售员",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-employee",
        "level": 5,
        "granularity": "finest",
        "reasoning": "销售员，组织维度最细粒度",
    },
    # ─────────────────────────────────────────────────────────
    # ORGANIZATION 组织维度 - 英文
    # ─────────────────────────────────────────────────────────
    {
        "field_caption": "company",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-company",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Organization dimension coarsest level, represents company",
    },
    {
        "field_caption": "Company",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-company",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Organization dimension coarsest level, represents company",
    },
    {
        "field_caption": "company_name",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-company",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Company name, organization dimension coarsest level",
    },
    {
        "field_caption": "saleper_company",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-department",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Sales department, organization dimension coarse level",
    },
    {
        "field_caption": "department",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-department",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Organization dimension coarse level, represents department",
    },
    {
        "field_caption": "Department",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-department",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Organization dimension coarse level, represents department",
    },
    {
        "field_caption": "division",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-division",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Division, organization dimension coarse level",
    },
    {
        "field_caption": "team",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-team",
        "level": 3,
        "granularity": "medium",
        "reasoning": "Organization dimension medium level, represents team",
    },
    {
        "field_caption": "Team",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-team",
        "level": 3,
        "granularity": "medium",
        "reasoning": "Organization dimension medium level, represents team",
    },
    {
        "field_caption": "employee",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-employee",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Organization dimension finest level, represents employee",
    },
    {
        "field_caption": "employee_name",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-employee",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Employee name, organization dimension finest level",
    },
    {
        "field_caption": "employee_id",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-employee",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Employee ID, organization dimension finest level",
    },
    {
        "field_caption": "sales_rep",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-employee",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Sales representative, organization dimension finest level",
    },
    {
        "field_caption": "salesperson",
        "data_type": "string",
        "category": "organization",
        "category_detail": "organization-employee",
        "level": 5,
        "granularity": "finest",
        "reasoning": "Salesperson, organization dimension finest level",
    },

    # ─────────────────────────────────────────────────────────
    # CHANNEL 渠道维度 - 中文
    # ─────────────────────────────────────────────────────────
    {
        "field_caption": "一级销售渠道",
        "data_type": "string",
        "category": "channel",
        "category_detail": "channel-level1",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "渠道维度最粗粒度，表示一级渠道",
    },
    {
        "field_caption": "渠道类型",
        "data_type": "string",
        "category": "channel",
        "category_detail": "channel-type",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "渠道维度最粗粒度，表示渠道类型",
    },
    {
        "field_caption": "二级销售渠道",
        "data_type": "string",
        "category": "channel",
        "category_detail": "channel-level2",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "渠道维度粗粒度，表示二级渠道",
    },
    {
        "field_caption": "内外销",
        "data_type": "string",
        "category": "channel",
        "category_detail": "channel-type",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "销售类型（集团内/外），渠道维度最粗粒度",
    },
    {
        "field_caption": "销售渠道",
        "data_type": "string",
        "category": "channel",
        "category_detail": "channel-level1",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "渠道维度最粗粒度，表示销售渠道",
    },
    # ─────────────────────────────────────────────────────────
    # CHANNEL 渠道维度 - 英文
    # ─────────────────────────────────────────────────────────
    {
        "field_caption": "channel",
        "data_type": "string",
        "category": "channel",
        "category_detail": "channel-level1",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Channel dimension coarsest level, represents channel",
    },
    {
        "field_caption": "Channel",
        "data_type": "string",
        "category": "channel",
        "category_detail": "channel-level1",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Channel dimension coarsest level, represents channel",
    },
    {
        "field_caption": "channel_type",
        "data_type": "string",
        "category": "channel",
        "category_detail": "channel-type",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Channel type, channel dimension coarsest level",
    },
    {
        "field_caption": "channel_1_name",
        "data_type": "string",
        "category": "channel",
        "category_detail": "channel-level1",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Level 1 channel name, channel dimension coarsest level",
    },
    {
        "field_caption": "sales_channel",
        "data_type": "string",
        "category": "channel",
        "category_detail": "channel-level1",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Sales channel, channel dimension coarsest level",
    },
    {
        "field_caption": "channel_2_name",
        "data_type": "string",
        "category": "channel",
        "category_detail": "channel-level2",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Level 2 channel name, channel dimension coarse level",
    },
    {
        "field_caption": "sub_channel",
        "data_type": "string",
        "category": "channel",
        "category_detail": "channel-level2",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Sub channel, channel dimension coarse level",
    },
    {
        "field_caption": "Ship Mode",
        "data_type": "string",
        "category": "channel",
        "category_detail": "channel-ship-mode",
        "level": 3,
        "granularity": "medium",
        "reasoning": "Ship mode, channel dimension medium level",
    },
    {
        "field_caption": "ship_mode",
        "data_type": "string",
        "category": "channel",
        "category_detail": "channel-ship-mode",
        "level": 3,
        "granularity": "medium",
        "reasoning": "Ship mode, channel dimension medium level",
    },

    # ─────────────────────────────────────────────────────────
    # FINANCIAL 财务维度 - 中文
    # ─────────────────────────────────────────────────────────
    {
        "field_caption": "科目类别",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-account-type",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "财务维度最粗粒度，表示科目大类",
    },
    {
        "field_caption": "成本中心",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-cost-center",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "财务维度粗粒度，表示成本中心",
    },
    {
        "field_caption": "科目",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-account",
        "level": 3,
        "granularity": "medium",
        "reasoning": "财务维度中等粒度，表示具体科目",
    },
    {
        "field_caption": "利润中心",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-profit-center",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "财务维度粗粒度，表示利润中心",
    },
    {
        "field_caption": "科目编码",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-account",
        "level": 4,
        "granularity": "fine",
        "reasoning": "财务维度细粒度，表示科目编码",
    },
    {
        "field_caption": "预算类型",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-budget-type",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "财务维度最粗粒度，表示预算类型",
    },
    # ─────────────────────────────────────────────────────────
    # FINANCIAL 财务维度 - 英文
    # ─────────────────────────────────────────────────────────
    {
        "field_caption": "account_type",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-account-type",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Financial dimension coarsest level, represents account type",
    },
    {
        "field_caption": "Account Type",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-account-type",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Financial dimension coarsest level, represents account type",
    },
    {
        "field_caption": "gl_account_type",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-account-type",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "GL account type, financial dimension coarsest level",
    },
    {
        "field_caption": "cost_center",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-cost-center",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Financial dimension coarse level, represents cost center",
    },
    {
        "field_caption": "Cost Center",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-cost-center",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Financial dimension coarse level, represents cost center",
    },
    {
        "field_caption": "cost_center_code",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-cost-center",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Cost center code, financial dimension coarse level",
    },
    {
        "field_caption": "profit_center",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-profit-center",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Profit center, financial dimension coarse level",
    },
    {
        "field_caption": "Profit Center",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-profit-center",
        "level": 2,
        "granularity": "coarse",
        "reasoning": "Profit center, financial dimension coarse level",
    },
    {
        "field_caption": "account",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-account",
        "level": 3,
        "granularity": "medium",
        "reasoning": "Financial dimension medium level, represents account",
    },
    {
        "field_caption": "Account",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-account",
        "level": 3,
        "granularity": "medium",
        "reasoning": "Financial dimension medium level, represents account",
    },
    {
        "field_caption": "gl_account",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-account",
        "level": 3,
        "granularity": "medium",
        "reasoning": "GL account, financial dimension medium level",
    },
    {
        "field_caption": "account_code",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-account",
        "level": 4,
        "granularity": "fine",
        "reasoning": "Account code, financial dimension fine level",
    },
    {
        "field_caption": "account_number",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-account",
        "level": 4,
        "granularity": "fine",
        "reasoning": "Account number, financial dimension fine level",
    },
    {
        "field_caption": "budget_type",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-budget-type",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Budget type, financial dimension coarsest level",
    },
    {
        "field_caption": "currency",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-currency",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Currency, financial dimension attribute",
    },
    {
        "field_caption": "Currency",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-currency",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Currency, financial dimension attribute",
    },
    {
        "field_caption": "currency_code",
        "data_type": "string",
        "category": "financial",
        "category_detail": "financial-currency",
        "level": 1,
        "granularity": "coarsest",
        "reasoning": "Currency code, financial dimension attribute",
    },
]


def get_seed_few_shot_examples(
    categories: List[str] = None,
    max_per_category: int = 1,
) -> List[Dict[str, Any]]:
    """
    获取种子数据作为 few-shot 示例
    
    Args:
        categories: 要获取的类别列表，None 表示所有类别
        max_per_category: 每个类别最多返回的示例数
    
    Returns:
        few-shot 示例列表
    """
    if categories is None:
        categories = ["time", "geography", "product", "customer", "organization", "channel", "financial"]
    
    examples = []
    category_counts = {cat: 0 for cat in categories}
    
    for pattern in SEED_PATTERNS:
        cat = pattern["category"]
        if cat in categories and category_counts[cat] < max_per_category:
            examples.append({
                "field_caption": pattern["field_caption"],
                "data_type": pattern["data_type"],
                "category": pattern["category"],
                "category_detail": pattern["category_detail"],
                "level": pattern["level"],
                "granularity": pattern["granularity"],
            })
            category_counts[cat] += 1
    
    return examples


__all__ = [
    "SEED_PATTERNS",
    "get_seed_few_shot_examples",
]
