# -*- coding: utf-8 -*-
"""Replan Models.

Data models for replanning.

Contains:
- ExplorationQuestion: Exploration question
- ReplanDecision: Replan decision
"""
from typing import List, Optional, Literal
from pydantic import BaseModel, Field, ConfigDict


class ExplorationQuestion(BaseModel):
    """Exploration question - Generated by Replanner LLM.
    
    <what>Single exploration question with text, type, target dimension and priority</what>
    
    <fill_order>
    1. question (ALWAYS)
    2. exploration_type (ALWAYS)
    3. target_dimension (ALWAYS)
    4. priority (ALWAYS)
    5. reasoning (ALWAYS)
    6. filter (optional)
    </fill_order>
    
    <examples>
    drill_down: {"question": "What is Store A's sales distribution by product category?", "exploration_type": "drill_down", "target_dimension": "Product Category", "priority": 2}
    time_series: {"question": "What is Store A's sales trend over the last 12 months?", "exploration_type": "time_series", "target_dimension": "Month", "priority": 1}
    </examples>
    
    <anti_patterns>
    X Using template placeholders: {"question": "{entity}'s sales"}
    X Repeating already answered questions
    </anti_patterns>
    """
    model_config = ConfigDict(extra="forbid")
    
    question: str = Field(
        description="""<what>Exploration question text (generated by LLM)</what>
<when>ALWAYS required</when>
<rule>Use specific entity names, not template placeholders</rule>
<must_not>Use {entity} or similar placeholders</must_not>"""
    )
    
    exploration_type: Literal[
        "drill_down",           # Drill down (category -> subcategory)
        "roll_up",              # Roll up (subcategory -> category)
        "time_series",          # Time series analysis
        "peer_comparison",      # Peer comparison
        "cross_dimension",      # Cross-dimension analysis
        "anomaly_investigation",# Anomaly investigation
        "correlation_analysis"  # Correlation analysis
    ] = Field(
        description="""<what>Exploration type</what>
<when>ALWAYS required</when>
<rule>
- drill_down: need finer granularity -> drill down
- roll_up: need coarser granularity -> roll up
- time_series: need temporal analysis -> time series
- peer_comparison: need horizontal comparison -> peer comparison
- cross_dimension: need multi-dimensional analysis -> cross dimension
- anomaly_investigation: found anomaly -> anomaly investigation
- correlation_analysis: need relationship analysis -> correlation
</rule>"""
    )
    
    target_dimension: str = Field(
        description="""<what>Target dimension</what>
<when>ALWAYS required</when>
<rule>Select from dimension_hierarchy</rule>
<dependency>Must exist in dimension_hierarchy</dependency>"""
    )
    
    filter: Optional[str] = Field(
        default=None,
        description="""<what>Filter condition</what>
<when>When scope restriction needed</when>"""
    )
    
    priority: float = Field(
        ge=0.0,
        le=1.0,
        description="""<what>Priority score</what>
<when>ALWAYS required</when>
<rule>0.9-1.0=directly answers user question, 0.7-0.9=key supporting info, 0.4-0.7=deepens understanding, 0.0-0.4=peripheral exploration</rule>"""
    )
    
    reasoning: str = Field(
        description="""<what>Reasoning explanation</what>
<when>ALWAYS required</when>
<rule>Explain why this question was generated</rule>"""
    )


class ReplanDecision(BaseModel):
    """Replan decision - Supports parallel multi-question execution.
    
    <what>Replan decision with completeness assessment and exploration question list</what>
    
    <fill_order>
    1. completeness_score (ALWAYS first)
    2. should_replan (ALWAYS)
    3. reason (ALWAYS)
    4. missing_aspects (if should_replan=True)
    5. exploration_questions (if should_replan=True)
    6. confidence (ALWAYS)
    </fill_order>
    
    <examples>
    Complete: {"completeness_score": 0.95, "should_replan": false, "reason": "Core question fully answered"}
    Needs replan: {"completeness_score": 0.6, "should_replan": true, "missing_aspects": ["time trend"], "exploration_questions": [...]}
    </examples>
    
    <anti_patterns>
    X completeness_score >= 0.9 but should_replan = true
    X should_replan = true but exploration_questions is empty
    </anti_patterns>
    """
    model_config = ConfigDict(extra="forbid")
    
    completeness_score: float = Field(
        ge=0.0,
        le=1.0,
        description="""<what>Analysis completeness score</what>
<when>ALWAYS required</when>
<rule>>=0.9 fully answered, 0.7-0.9 mostly answered, <0.7 needs replan</rule>"""
    )
    
    should_replan: bool = Field(
        description="""<what>Whether replan is needed</what>
<when>ALWAYS required</when>
<rule>completeness_score < 0.9 -> true</rule>
<dependency>Consistent with completeness_score</dependency>"""
    )
    
    reason: str = Field(
        description="""<what>Assessment reason</what>
<when>ALWAYS required</when>
<rule>Explain why replan is/isn't needed</rule>"""
    )
    
    missing_aspects: List[str] = Field(
        default_factory=list,
        description="""<what>Missing analysis aspects</what>
<when>Required when should_replan=True</when>
<dependency>should_replan == True</dependency>"""
    )
    
    exploration_questions: List[ExplorationQuestion] = Field(
        default_factory=list,
        description="""<what>Exploration question list</what>
<when>Required when should_replan=True</when>
<rule>Maximum 5 questions, sorted by priority</rule>
<dependency>should_replan == True</dependency>"""
    )
    
    parallel_execution: bool = Field(
        default=True,
        description="""<what>Whether to execute in parallel</what>
<when>Default True</when>"""
    )
    
    max_questions_per_round: int = Field(
        default=3,
        ge=1,
        le=5,
        description="""<what>Max questions per round</what>
<when>Default 3</when>"""
    )
    
    confidence: float = Field(
        default=0.8,
        ge=0.0,
        le=1.0,
        description="""<what>Decision confidence</what>
<when>ALWAYS required</when>"""
    )
    
    def get_top_questions(self, n: int = 3) -> List[ExplorationQuestion]:
        """Get top N questions by priority (higher score = higher priority)."""
        sorted_questions = sorted(self.exploration_questions, key=lambda q: q.priority, reverse=True)
        return sorted_questions[:n]
    
    def get_questions_by_type(self, exploration_type: str) -> List[ExplorationQuestion]:
        """Filter questions by exploration type."""
        return [q for q in self.exploration_questions if q.exploration_type == exploration_type]


__all__ = [
    "ExplorationQuestion",
    "ReplanDecision",
]
