# -*- coding: utf-8 -*-
"""渠道维度种子数据（一级渠道、二级渠道等）"""
from ._types import DimensionSeed

_CHANNEL_SEEDS: list[DimensionSeed] = [
    DimensionSeed(
        field_caption="一级销售渠道",
        data_type="string",
        category="channel",
        category_detail="channel-level1",
        level=1,
        business_description="一级销售渠道，渠道维度最粗粒度",
        aliases=["一级渠道", "Primary Channel", "主渠道"],
        reasoning="渠道维度最粗粒度，表示一级渠道",
    ),
    DimensionSeed(
        field_caption="销售渠道",
        data_type="string",
        category="channel",
        category_detail="channel-level1",
        level=1,
        business_description="销售渠道，渠道维度最粗粒度",
        aliases=["渠道", "Sales Channel", "渠道类型"],
        reasoning="渠道维度最粗粒度，表示销售渠道",
    ),
    DimensionSeed(
        field_caption="channel",
        data_type="string",
        category="channel",
        category_detail="channel-level1",
        level=1,
        business_description="Channel, coarsest channel dimension",
        aliases=["渠道", "Channel", "销售渠道"],
        reasoning="Channel dimension coarsest level, represents channel",
    ),
    DimensionSeed(
        field_caption="channel_1_name",
        data_type="string",
        category="channel",
        category_detail="channel-level1",
        level=1,
        business_description="Level 1 channel name",
        aliases=["一级渠道", "Primary Channel", "一级渠道名称"],
        reasoning="Level 1 channel name, channel dimension coarsest level",
    ),
    DimensionSeed(
        field_caption="sales_channel",
        data_type="string",
        category="channel",
        category_detail="channel-level1",
        level=1,
        business_description="Sales channel for distribution",
        aliases=["销售渠道", "Sales Channel", "渠道"],
        reasoning="Sales channel, channel dimension coarsest level",
    ),
    DimensionSeed(
        field_caption="渠道类型",
        data_type="string",
        category="channel",
        category_detail="channel-type",
        level=1,
        business_description="渠道类型，渠道维度最粗粒度",
        aliases=["渠道分类", "Channel Type", "渠道"],
        reasoning="渠道维度最粗粒度，表示渠道类型",
    ),
    DimensionSeed(
        field_caption="内外销",
        data_type="string",
        category="channel",
        category_detail="channel-type",
        level=1,
        business_description="销售类型（集团内/外），渠道维度最粗粒度",
        aliases=["内销外销", "Domestic/Export", "销售类型"],
        reasoning="销售类型（集团内/外），渠道维度最粗粒度",
    ),
    DimensionSeed(
        field_caption="channel_type",
        data_type="string",
        category="channel",
        category_detail="channel-type",
        level=1,
        business_description="Channel type for classification",
        aliases=["渠道类型", "Channel Type", "渠道分类"],
        reasoning="Channel type, channel dimension coarsest level",
    ),
    DimensionSeed(
        field_caption="二级销售渠道",
        data_type="string",
        category="channel",
        category_detail="channel-level2",
        level=2,
        business_description="二级销售渠道，渠道维度粗粒度",
        aliases=["二级渠道", "Secondary Channel", "子渠道"],
        reasoning="渠道维度粗粒度，表示二级渠道",
    ),
    DimensionSeed(
        field_caption="channel_2_name",
        data_type="string",
        category="channel",
        category_detail="channel-level2",
        level=2,
        business_description="Level 2 channel name",
        aliases=["二级渠道", "Secondary Channel", "二级渠道名称"],
        reasoning="Level 2 channel name, channel dimension coarse level",
    ),
    DimensionSeed(
        field_caption="sub_channel",
        data_type="string",
        category="channel",
        category_detail="channel-level2",
        level=2,
        business_description="Sub channel for detailed classification",
        aliases=["子渠道", "Sub Channel", "二级渠道"],
        reasoning="Sub channel, channel dimension coarse level",
    ),
    DimensionSeed(
        field_caption="Ship Mode",
        data_type="string",
        category="channel",
        category_detail="channel-ship-mode",
        level=3,
        business_description="Shipping mode for delivery",
        aliases=["配送方式", "Shipping Mode", "运输方式"],
        reasoning="Ship mode, channel dimension medium level",
    ),
    DimensionSeed(
        field_caption="ship_mode",
        data_type="string",
        category="channel",
        category_detail="channel-ship-mode",
        level=3,
        business_description="Shipping mode for delivery",
        aliases=["配送方式", "Ship Mode", "运输方式"],
        reasoning="Ship mode, channel dimension medium level",
    ),
]
