# -*- coding: utf-8 -*-
"""通用维度种子数据（订单、合同、状态、标签等）"""
from ._types import DimensionSeed

_COMMON_SEEDS: list[DimensionSeed] = [
    DimensionSeed(
        field_caption="合同号",
        data_type="string",
        category="contract",
        category_detail="contract-id",
        level=5,
        business_description="合同唯一编号",
        aliases=["contract_id", "Contract ID", "合同编号", "合同ID"],
        reasoning="合同号，合同维度最细粒度",
    ),
    DimensionSeed(
        field_caption="contract_id",
        data_type="string",
        category="contract",
        category_detail="contract-id",
        level=5,
        business_description="Contract unique identifier",
        aliases=["Contract ID", "合同号", "合同编号"],
        reasoning="Contract ID, contract dimension finest level",
    ),
    DimensionSeed(
        field_caption="合同类型",
        data_type="string",
        category="contract",
        category_detail="contract-type",
        level=2,
        business_description="合同的分类类型",
        aliases=["contract_type", "Contract Type"],
        reasoning="合同类型，合同维度粗粒度",
    ),
    DimensionSeed(
        field_caption="contract_type",
        data_type="string",
        category="contract",
        category_detail="contract-type",
        level=2,
        business_description="Type classification of contracts",
        aliases=["Contract Type", "合同类型"],
        reasoning="Contract type, contract dimension coarse level",
    ),
    DimensionSeed(
        field_caption="描述",
        data_type="string",
        category="description",
        category_detail="description-general",
        level=4,
        business_description="通用描述字段",
        aliases=["description", "Description", "说明", "备注"],
        reasoning="描述，通用维度细粒度",
    ),
    DimensionSeed(
        field_caption="description",
        data_type="string",
        category="description",
        category_detail="description-general",
        level=4,
        business_description="Generic description field",
        aliases=["Description", "描述", "说明"],
        reasoning="Description, general dimension fine level",
    ),
    DimensionSeed(
        field_caption="notes",
        data_type="string",
        category="description",
        category_detail="description-notes",
        level=4,
        business_description="Notes or remarks",
        aliases=["Notes", "备注", "remarks"],
        reasoning="Notes, description dimension fine level",
    ),
    DimensionSeed(
        field_caption="编码",
        data_type="string",
        category="identifier",
        category_detail="identifier-code",
        level=5,
        business_description="通用编码标识符",
        aliases=["code", "Code", "编号"],
        reasoning="通用编码，标识符维度",
    ),
    DimensionSeed(
        field_caption="code",
        data_type="string",
        category="identifier",
        category_detail="identifier-code",
        level=5,
        business_description="Generic code identifier",
        aliases=["编码", "Code", "编号"],
        reasoning="Generic code, identifier dimension",
    ),
    DimensionSeed(
        field_caption="ID",
        data_type="string",
        category="identifier",
        category_detail="identifier-id",
        level=5,
        business_description="通用唯一标识符",
        aliases=["id", "标识", "标识符"],
        reasoning="通用ID，标识符维度",
    ),
    DimensionSeed(
        field_caption="行业",
        data_type="string",
        category="industry",
        category_detail="industry-general",
        level=1,
        business_description="行业分类",
        aliases=["industry", "Industry", "行业类型"],
        reasoning="行业，行业维度最粗粒度",
    ),
    DimensionSeed(
        field_caption="industry",
        data_type="string",
        category="industry",
        category_detail="industry-general",
        level=1,
        business_description="Industry classification",
        aliases=["Industry", "行业", "sector"],
        reasoning="Industry, industry dimension coarsest level",
    ),
    DimensionSeed(
        field_caption="发票号",
        data_type="string",
        category="invoice",
        category_detail="invoice-id",
        level=5,
        business_description="发票唯一编号",
        aliases=["invoice_id", "Invoice ID", "发票编号"],
        reasoning="发票号，发票维度最细粒度",
    ),
    DimensionSeed(
        field_caption="invoice_id",
        data_type="string",
        category="invoice",
        category_detail="invoice-id",
        level=5,
        business_description="Invoice unique identifier",
        aliases=["Invoice ID", "发票号", "发票编号"],
        reasoning="Invoice ID, invoice dimension finest level",
    ),
    DimensionSeed(
        field_caption="仓库",
        data_type="string",
        category="logistics",
        category_detail="logistics-warehouse",
        level=3,
        business_description="仓库名称",
        aliases=["warehouse", "Warehouse", "库房", "仓储"],
        reasoning="仓库，物流维度中等粒度",
    ),
    DimensionSeed(
        field_caption="warehouse",
        data_type="string",
        category="logistics",
        category_detail="logistics-warehouse",
        level=3,
        business_description="Warehouse name",
        aliases=["Warehouse", "仓库", "库房"],
        reasoning="Warehouse, logistics dimension medium level",
    ),
    DimensionSeed(
        field_caption="仓库编码",
        data_type="string",
        category="logistics",
        category_detail="logistics-warehouse",
        level=5,
        business_description="仓库唯一编码",
        aliases=["warehouse_id", "Warehouse ID", "仓库ID"],
        reasoning="仓库编码，物流维度最细粒度",
    ),
    DimensionSeed(
        field_caption="warehouse_id",
        data_type="string",
        category="logistics",
        category_detail="logistics-warehouse",
        level=5,
        business_description="Warehouse unique identifier",
        aliases=["Warehouse ID", "仓库ID", "仓库编码"],
        reasoning="Warehouse ID, logistics dimension finest level",
    ),
    DimensionSeed(
        field_caption="名称",
        data_type="string",
        category="name",
        category_detail="name-general",
        level=3,
        business_description="通用名称字段",
        aliases=["name", "Name", "名字"],
        reasoning="名称，通用维度中等粒度",
    ),
    DimensionSeed(
        field_caption="name",
        data_type="string",
        category="name",
        category_detail="name-general",
        level=3,
        business_description="Generic name field",
        aliases=["Name", "名称", "名字"],
        reasoning="Name, general dimension medium level",
    ),
    DimensionSeed(
        field_caption="付款方式",
        data_type="string",
        category="payment",
        category_detail="payment-method",
        level=2,
        business_description="支付方式类型",
        aliases=["payment_method", "Payment Method", "支付方式"],
        reasoning="付款方式，支付维度粗粒度",
    ),
    DimensionSeed(
        field_caption="payment_method",
        data_type="string",
        category="payment",
        category_detail="payment-method",
        level=2,
        business_description="Payment method type",
        aliases=["Payment Method", "付款方式", "支付方式"],
        reasoning="Payment method, payment dimension coarse level",
    ),
    DimensionSeed(
        field_caption="优先级",
        data_type="string",
        category="priority",
        category_detail="priority-general",
        level=2,
        business_description="优先级别",
        aliases=["priority", "Priority", "级别"],
        reasoning="优先级，优先级维度粗粒度",
    ),
    DimensionSeed(
        field_caption="priority",
        data_type="string",
        category="priority",
        category_detail="priority-general",
        level=2,
        business_description="Priority level",
        aliases=["Priority", "优先级", "level"],
        reasoning="Priority, priority dimension coarse level",
    ),
    DimensionSeed(
        field_caption="项目",
        data_type="string",
        category="project",
        category_detail="project-name",
        level=3,
        business_description="项目名称",
        aliases=["project", "Project", "项目名称"],
        reasoning="项目，项目维度中等粒度",
    ),
    DimensionSeed(
        field_caption="project",
        data_type="string",
        category="project",
        category_detail="project-name",
        level=3,
        business_description="Project name",
        aliases=["Project", "项目", "项目名称"],
        reasoning="Project, project dimension medium level",
    ),
    DimensionSeed(
        field_caption="项目编码",
        data_type="string",
        category="project",
        category_detail="project-id",
        level=5,
        business_description="项目唯一编码",
        aliases=["project_id", "Project ID", "项目ID"],
        reasoning="项目编码，项目维度最细粒度",
    ),
    DimensionSeed(
        field_caption="project_id",
        data_type="string",
        category="project",
        category_detail="project-id",
        level=5,
        business_description="Project unique identifier",
        aliases=["Project ID", "项目ID", "项目编码"],
        reasoning="Project ID, project dimension finest level",
    ),
    DimensionSeed(
        field_caption="来源",
        data_type="string",
        category="source",
        category_detail="source-general",
        level=2,
        business_description="数据或业务来源",
        aliases=["source", "Source", "数据来源", "渠道来源"],
        reasoning="来源，来源维度粗粒度",
    ),
    DimensionSeed(
        field_caption="source",
        data_type="string",
        category="source",
        category_detail="source-general",
        level=2,
        business_description="Data or business source",
        aliases=["Source", "来源", "数据来源"],
        reasoning="Source, source dimension coarse level",
    ),
    DimensionSeed(
        field_caption="状态",
        data_type="string",
        category="status",
        category_detail="status-general",
        level=3,
        business_description="通用状态字段",
        aliases=["status", "Status", "状态码"],
        reasoning="状态，通用维度",
    ),
    DimensionSeed(
        field_caption="status",
        data_type="string",
        category="status",
        category_detail="status-general",
        level=3,
        business_description="Generic status field",
        aliases=["Status", "状态", "state"],
        reasoning="Status, general dimension",
    ),
    DimensionSeed(
        field_caption="供应商",
        data_type="string",
        category="supplier",
        category_detail="supplier-name",
        level=3,
        business_description="供应商名称",
        aliases=["supplier", "Supplier", "供货商", "vendor"],
        reasoning="供应商，供应商维度中等粒度",
    ),
    DimensionSeed(
        field_caption="supplier",
        data_type="string",
        category="supplier",
        category_detail="supplier-name",
        level=3,
        business_description="Supplier name",
        aliases=["Supplier", "供应商", "vendor"],
        reasoning="Supplier, supplier dimension medium level",
    ),
    DimensionSeed(
        field_caption="vendor",
        data_type="string",
        category="supplier",
        category_detail="supplier-name",
        level=3,
        business_description="Vendor name",
        aliases=["Vendor", "供应商", "supplier"],
        reasoning="Vendor, supplier dimension medium level",
    ),
    DimensionSeed(
        field_caption="供应商编码",
        data_type="string",
        category="supplier",
        category_detail="supplier-id",
        level=5,
        business_description="供应商唯一编码",
        aliases=["supplier_id", "Supplier ID", "供应商ID"],
        reasoning="供应商编码，供应商维度最细粒度",
    ),
    DimensionSeed(
        field_caption="supplier_id",
        data_type="string",
        category="supplier",
        category_detail="supplier-id",
        level=5,
        business_description="Supplier unique identifier",
        aliases=["Supplier ID", "供应商ID", "供应商编码"],
        reasoning="Supplier ID, supplier dimension finest level",
    ),
    DimensionSeed(
        field_caption="标签",
        data_type="string",
        category="tag",
        category_detail="tag-general",
        level=3,
        business_description="标签分类",
        aliases=["tag", "Tag", "tags"],
        reasoning="标签，标签维度中等粒度",
    ),
    DimensionSeed(
        field_caption="tag",
        data_type="string",
        category="tag",
        category_detail="tag-general",
        level=3,
        business_description="Tag classification",
        aliases=["Tag", "标签", "label"],
        reasoning="Tag, tag dimension medium level",
    ),
    DimensionSeed(
        field_caption="订单号",
        data_type="string",
        category="transaction",
        category_detail="transaction-order",
        level=5,
        business_description="订单的唯一编号",
        aliases=["order_id", "Order ID", "订单ID", "订单编号"],
        reasoning="订单号，交易维度最细粒度",
    ),
    DimensionSeed(
        field_caption="order_id",
        data_type="string",
        category="transaction",
        category_detail="transaction-order",
        level=5,
        business_description="Unique order identifier",
        aliases=["Order ID", "订单号", "订单ID"],
        reasoning="Order ID, transaction dimension finest level",
    ),
    DimensionSeed(
        field_caption="Order ID",
        data_type="string",
        category="transaction",
        category_detail="transaction-order",
        level=5,
        business_description="Unique order identifier",
        aliases=["order_id", "订单号", "订单ID"],
        reasoning="Order ID, transaction dimension finest level",
    ),
    DimensionSeed(
        field_caption="订单类型",
        data_type="string",
        category="transaction",
        category_detail="transaction-order-type",
        level=2,
        business_description="订单的分类类型",
        aliases=["order_type", "Order Type"],
        reasoning="订单类型，交易维度粗粒度",
    ),
    DimensionSeed(
        field_caption="order_type",
        data_type="string",
        category="transaction",
        category_detail="transaction-order-type",
        level=2,
        business_description="Type classification of orders",
        aliases=["Order Type", "订单类型"],
        reasoning="Order type, transaction dimension coarse level",
    ),
    DimensionSeed(
        field_caption="订单状态",
        data_type="string",
        category="transaction",
        category_detail="transaction-status",
        level=3,
        business_description="订单的当前状态",
        aliases=["order_status", "Order Status", "状态"],
        reasoning="订单状态，交易维度中等粒度",
    ),
    DimensionSeed(
        field_caption="order_status",
        data_type="string",
        category="transaction",
        category_detail="transaction-status",
        level=3,
        business_description="Current status of order",
        aliases=["Order Status", "订单状态", "status"],
        reasoning="Order status, transaction dimension medium level",
    ),
    DimensionSeed(
        field_caption="类型",
        data_type="string",
        category="type",
        category_detail="type-general",
        level=2,
        business_description="通用类型分类",
        aliases=["type", "Type", "分类"],
        reasoning="类型，通用维度粗粒度",
    ),
    DimensionSeed(
        field_caption="type",
        data_type="string",
        category="type",
        category_detail="type-general",
        level=2,
        business_description="Generic type classification",
        aliases=["Type", "类型", "分类"],
        reasoning="Type, general dimension coarse level",
    ),
]
