# -*- coding: utf-8 -*-
"""客户维度种子数据（客户类型、客户名称等）"""
from ._types import DimensionSeed

_CUSTOMER_SEEDS: list[DimensionSeed] = [
    DimensionSeed(
        field_caption="客户类型",
        data_type="string",
        category="customer",
        category_detail="customer-type",
        level=1,
        business_description="表示客户类型，客户维度最粗粒度",
        aliases=["客户分类", "Customer Type", "类型"],
        reasoning="客户维度最粗粒度，表示客户类型",
    ),
    DimensionSeed(
        field_caption="customer_type",
        data_type="string",
        category="customer",
        category_detail="customer-type",
        level=1,
        business_description="Customer type, coarsest customer dimension",
        aliases=["客户类型", "Customer Type", "类型"],
        reasoning="Customer dimension coarsest level, represents customer type",
    ),
    DimensionSeed(
        field_caption="Customer Type",
        data_type="string",
        category="customer",
        category_detail="customer-type",
        level=1,
        business_description="Customer type, coarsest customer dimension",
        aliases=["客户类型", "customer_type", "类型"],
        reasoning="Customer dimension coarsest level, represents customer type",
    ),
    DimensionSeed(
        field_caption="客户分类",
        data_type="string",
        category="customer",
        category_detail="customer-segment",
        level=2,
        business_description="表示客户分类，客户维度粗粒度",
        aliases=["客户类型", "Customer Segment", "分类"],
        reasoning="客户维度粗粒度，表示客户分类",
    ),
    DimensionSeed(
        field_caption="segment",
        data_type="string",
        category="customer",
        category_detail="customer-segment",
        level=2,
        business_description="Customer segment, coarse customer dimension",
        aliases=["客户分类", "Segment", "分类"],
        reasoning="Customer segment, customer dimension coarse level",
    ),
    DimensionSeed(
        field_caption="customer_segment",
        data_type="string",
        category="customer",
        category_detail="customer-segment",
        level=2,
        business_description="Customer segment for classification",
        aliases=["客户分类", "Segment", "客户类型"],
        reasoning="Customer segment, customer dimension coarse level",
    ),
    DimensionSeed(
        field_caption="客户名称",
        data_type="string",
        category="customer",
        category_detail="customer-name",
        level=3,
        business_description="表示客户名称，客户维度中等粒度",
        aliases=["客户", "Customer Name", "客户名"],
        reasoning="客户维度中等粒度，表示客户名称",
    ),
    DimensionSeed(
        field_caption="customer_name",
        data_type="string",
        category="customer",
        category_detail="customer-name",
        level=3,
        business_description="Customer name for identification",
        aliases=["客户名称", "Customer", "客户"],
        reasoning="Customer name, customer dimension medium level",
    ),
    DimensionSeed(
        field_caption="Customer Name",
        data_type="string",
        category="customer",
        category_detail="customer-name",
        level=3,
        business_description="Customer name for identification",
        aliases=["客户名称", "customer_name", "客户"],
        reasoning="Customer name, customer dimension medium level",
    ),
    DimensionSeed(
        field_caption="客户ID",
        data_type="string",
        category="customer",
        category_detail="customer-id",
        level=5,
        business_description="客户唯一标识，客户维度最细粒度",
        aliases=["客户编码", "Customer ID", "客户号"],
        reasoning="客户维度最细粒度，表示客户唯一标识",
    ),
    DimensionSeed(
        field_caption="客户编码",
        data_type="string",
        category="customer",
        category_detail="customer-id",
        level=5,
        business_description="客户编码，客户维度最细粒度",
        aliases=["客户ID", "Customer Code", "客户号"],
        reasoning="客户维度最细粒度，表示客户编码",
    ),
    DimensionSeed(
        field_caption="customer_id",
        data_type="string",
        category="customer",
        category_detail="customer-id",
        level=5,
        business_description="Customer unique identifier",
        aliases=["客户ID", "Customer ID", "客户编码"],
        reasoning="Customer ID, customer dimension finest level",
    ),
    DimensionSeed(
        field_caption="Customer ID",
        data_type="string",
        category="customer",
        category_detail="customer-id",
        level=5,
        business_description="Customer unique identifier",
        aliases=["客户ID", "customer_id", "客户编码"],
        reasoning="Customer ID, customer dimension finest level",
    ),
    DimensionSeed(
        field_caption="sold_to",
        data_type="string",
        category="customer",
        category_detail="customer-id",
        level=5,
        business_description="Sold-to party code for customer",
        aliases=["售达方", "Sold To", "客户代码"],
        reasoning="Sold-to party code, customer dimension finest level",
    ),
    DimensionSeed(
        field_caption="ship_to",
        data_type="string",
        category="customer",
        category_detail="customer-id",
        level=5,
        business_description="Ship-to party code for delivery",
        aliases=["送达方", "Ship To", "收货方"],
        reasoning="Ship-to party code, customer dimension finest level",
    ),
    DimensionSeed(
        field_caption="客户等级",
        data_type="string",
        category="customer",
        category_detail="customer-tier",
        level=2,
        business_description="客户的等级分类",
        aliases=["customer_tier", "Customer Tier", "客户级别", "会员等级"],
        reasoning="客户等级，客户维度粗粒度",
    ),
]
