# -*- coding: utf-8 -*-
"""财务维度种子数据（科目、成本中心等）"""
from ._types import DimensionSeed

_FINANCIAL_SEEDS: list[DimensionSeed] = [
    DimensionSeed(
        field_caption="科目类别",
        data_type="string",
        category="financial",
        category_detail="financial-account-type",
        level=1,
        business_description="科目大类，财务维度最粗粒度",
        aliases=["科目分类", "Account Type", "会计科目类别"],
        reasoning="财务维度最粗粒度，表示科目大类",
    ),
    DimensionSeed(
        field_caption="account_type",
        data_type="string",
        category="financial",
        category_detail="financial-account-type",
        level=1,
        business_description="Account type, coarsest financial dimension",
        aliases=["科目类别", "Account Type", "科目分类"],
        reasoning="Financial dimension coarsest level, represents account type",
    ),
    DimensionSeed(
        field_caption="Account Type",
        data_type="string",
        category="financial",
        category_detail="financial-account-type",
        level=1,
        business_description="Account type, coarsest financial dimension",
        aliases=["科目类别", "account_type", "科目分类"],
        reasoning="Financial dimension coarsest level, represents account type",
    ),
    DimensionSeed(
        field_caption="gl_account_type",
        data_type="string",
        category="financial",
        category_detail="financial-account-type",
        level=1,
        business_description="GL account type for classification",
        aliases=["总账科目类型", "GL Account Type", "科目类型"],
        reasoning="GL account type, financial dimension coarsest level",
    ),
    DimensionSeed(
        field_caption="成本中心",
        data_type="string",
        category="financial",
        category_detail="financial-cost-center",
        level=2,
        business_description="成本中心，财务维度粗粒度",
        aliases=["成本中心代码", "Cost Center", "成本归集点"],
        reasoning="财务维度粗粒度，表示成本中心",
    ),
    DimensionSeed(
        field_caption="cost_center",
        data_type="string",
        category="financial",
        category_detail="financial-cost-center",
        level=2,
        business_description="Cost center for expense allocation",
        aliases=["成本中心", "Cost Center", "成本归集点"],
        reasoning="Financial dimension coarse level, represents cost center",
    ),
    DimensionSeed(
        field_caption="Cost Center",
        data_type="string",
        category="financial",
        category_detail="financial-cost-center",
        level=2,
        business_description="Cost center for expense allocation",
        aliases=["成本中心", "cost_center", "成本归集点"],
        reasoning="Financial dimension coarse level, represents cost center",
    ),
    DimensionSeed(
        field_caption="cost_center_code",
        data_type="string",
        category="financial",
        category_detail="financial-cost-center",
        level=2,
        business_description="Cost center code for identification",
        aliases=["成本中心代码", "Cost Center Code", "成本中心编码"],
        reasoning="Cost center code, financial dimension coarse level",
    ),
    DimensionSeed(
        field_caption="科目",
        data_type="string",
        category="financial",
        category_detail="financial-account",
        level=3,
        business_description="具体科目，财务维度中等粒度",
        aliases=["会计科目", "Account", "科目名称"],
        reasoning="财务维度中等粒度，表示具体科目",
    ),
    DimensionSeed(
        field_caption="account",
        data_type="string",
        category="financial",
        category_detail="financial-account",
        level=3,
        business_description="Account for financial tracking",
        aliases=["科目", "Account", "会计科目"],
        reasoning="Financial dimension medium level, represents account",
    ),
    DimensionSeed(
        field_caption="gl_account",
        data_type="string",
        category="financial",
        category_detail="financial-account",
        level=3,
        business_description="GL account for ledger tracking",
        aliases=["总账科目", "GL Account", "科目"],
        reasoning="GL account, financial dimension medium level",
    ),
    DimensionSeed(
        field_caption="利润中心",
        data_type="string",
        category="financial",
        category_detail="financial-profit-center",
        level=2,
        business_description="利润中心，财务维度粗粒度",
        aliases=["利润中心代码", "Profit Center", "利润归集点"],
        reasoning="财务维度粗粒度，表示利润中心",
    ),
    DimensionSeed(
        field_caption="profit_center",
        data_type="string",
        category="financial",
        category_detail="financial-profit-center",
        level=2,
        business_description="Profit center for revenue allocation",
        aliases=["利润中心", "Profit Center", "利润归集点"],
        reasoning="Profit center, financial dimension coarse level",
    ),
    DimensionSeed(
        field_caption="Profit Center",
        data_type="string",
        category="financial",
        category_detail="financial-profit-center",
        level=2,
        business_description="Profit center for revenue allocation",
        aliases=["利润中心", "profit_center", "利润归集点"],
        reasoning="Profit center, financial dimension coarse level",
    ),
    DimensionSeed(
        field_caption="科目编码",
        data_type="string",
        category="financial",
        category_detail="financial-account",
        level=4,
        business_description="科目编码，财务维度细粒度",
        aliases=["科目代码", "Account Code", "会计科目编码"],
        reasoning="财务维度细粒度，表示科目编码",
    ),
    DimensionSeed(
        field_caption="account_code",
        data_type="string",
        category="financial",
        category_detail="financial-account",
        level=4,
        business_description="Account code for identification",
        aliases=["科目编码", "Account Code", "科目代码"],
        reasoning="Account code, financial dimension fine level",
    ),
    DimensionSeed(
        field_caption="account_number",
        data_type="string",
        category="financial",
        category_detail="financial-account",
        level=4,
        business_description="Account number for identification",
        aliases=["科目号", "Account Number", "科目编号"],
        reasoning="Account number, financial dimension fine level",
    ),
    DimensionSeed(
        field_caption="预算类型",
        data_type="string",
        category="financial",
        category_detail="financial-budget-type",
        level=1,
        business_description="预算类型，财务维度最粗粒度",
        aliases=["预算分类", "Budget Type", "预算类别"],
        reasoning="财务维度最粗粒度，表示预算类型",
    ),
    DimensionSeed(
        field_caption="budget_type",
        data_type="string",
        category="financial",
        category_detail="financial-budget-type",
        level=1,
        business_description="Budget type for planning",
        aliases=["预算类型", "Budget Type", "预算分类"],
        reasoning="Budget type, financial dimension coarsest level",
    ),
    DimensionSeed(
        field_caption="currency",
        data_type="string",
        category="financial",
        category_detail="financial-currency",
        level=1,
        business_description="Currency for transactions",
        aliases=["货币", "Currency", "币种"],
        reasoning="Currency, financial dimension attribute",
    ),
    DimensionSeed(
        field_caption="currency_code",
        data_type="string",
        category="financial",
        category_detail="financial-currency",
        level=1,
        business_description="Currency code for identification",
        aliases=["货币代码", "Currency Code", "币种代码"],
        reasoning="Currency code, financial dimension attribute",
    ),
]
