# -*- coding: utf-8 -*-
"""地理维度种子数据（国家、省份、城市、区县等）"""
from ._types import DimensionSeed

_GEOGRAPHY_SEEDS: list[DimensionSeed] = [
    DimensionSeed(
        field_caption="国家",
        data_type="string",
        category="geography",
        category_detail="geography-country",
        level=1,
        business_description="表示国家，地理维度最粗粒度",
        aliases=["国", "Country", "国家名称"],
        reasoning="地理维度最粗粒度，表示国家",
    ),
    DimensionSeed(
        field_caption="country",
        data_type="string",
        category="geography",
        category_detail="geography-country",
        level=1,
        business_description="Represents country, coarsest geography dimension",
        aliases=["国家", "Country", "nation"],
        reasoning="Geography dimension coarsest level, represents country",
    ),
    DimensionSeed(
        field_caption="country_name",
        data_type="string",
        category="geography",
        category_detail="geography-country",
        level=1,
        business_description="Country name for display",
        aliases=["国家名称", "Country", "国家"],
        reasoning="Country name, geography dimension coarsest level",
    ),
    DimensionSeed(
        field_caption="省份",
        data_type="string",
        category="geography",
        category_detail="geography-province",
        level=2,
        business_description="表示省份，地理维度粗粒度",
        aliases=["省", "Province", "省区"],
        reasoning="地理维度粗粒度，表示省份",
    ),
    DimensionSeed(
        field_caption="省区",
        data_type="string",
        category="geography",
        category_detail="geography-province",
        level=2,
        business_description="表示省/区，地理维度粗粒度",
        aliases=["省份", "Province", "省"],
        reasoning="地理维度粗粒度，表示省/区",
    ),
    DimensionSeed(
        field_caption="客户省",
        data_type="string",
        category="geography",
        category_detail="geography-province",
        level=2,
        business_description="客户所在省份",
        aliases=["客户省份", "Customer Province", "省"],
        reasoning="客户所在省份，地理维度粗粒度",
    ),
    DimensionSeed(
        field_caption="state",
        data_type="string",
        category="geography",
        category_detail="geography-province",
        level=2,
        business_description="State or province, coarse geography dimension",
        aliases=["省份", "State", "省"],
        reasoning="State/Province, geography dimension coarse level",
    ),
    DimensionSeed(
        field_caption="province",
        data_type="string",
        category="geography",
        category_detail="geography-province",
        level=2,
        business_description="Province, coarse geography dimension",
        aliases=["省份", "Province", "省"],
        reasoning="Province, geography dimension coarse level",
    ),
    DimensionSeed(
        field_caption="城市",
        data_type="string",
        category="geography",
        category_detail="geography-city",
        level=3,
        business_description="表示城市，地理维度中等粒度",
        aliases=["市", "City", "城市名称"],
        reasoning="地理维度中等粒度，表示城市",
    ),
    DimensionSeed(
        field_caption="city",
        data_type="string",
        category="geography",
        category_detail="geography-city",
        level=3,
        business_description="Represents city, medium geography dimension",
        aliases=["城市", "City", "市"],
        reasoning="Geography dimension medium level, represents city",
    ),
    DimensionSeed(
        field_caption="city_name",
        data_type="string",
        category="geography",
        category_detail="geography-city",
        level=3,
        business_description="City name for display",
        aliases=["城市名称", "City", "城市"],
        reasoning="City name, geography dimension medium level",
    ),
    DimensionSeed(
        field_caption="区县",
        data_type="string",
        category="geography",
        category_detail="geography-district",
        level=4,
        business_description="表示区县，地理维度细粒度",
        aliases=["区", "县", "District"],
        reasoning="地理维度细粒度，表示区县",
    ),
    DimensionSeed(
        field_caption="客户区",
        data_type="string",
        category="geography",
        category_detail="geography-district",
        level=4,
        business_description="客户所在区县",
        aliases=["客户区县", "Customer District", "区"],
        reasoning="客户所在区县，地理维度细粒度",
    ),
    DimensionSeed(
        field_caption="district",
        data_type="string",
        category="geography",
        category_detail="geography-district",
        level=4,
        business_description="Represents district, fine geography dimension",
        aliases=["区县", "District", "区"],
        reasoning="Geography dimension fine level, represents district",
    ),
    DimensionSeed(
        field_caption="地区",
        data_type="string",
        category="geography",
        category_detail="geography-region",
        level=2,
        business_description="表示地区，地理维度粗粒度",
        aliases=["区域", "Region", "大区"],
        reasoning="地理维度粗粒度，表示地区",
    ),
    DimensionSeed(
        field_caption="region",
        data_type="string",
        category="geography",
        category_detail="geography-region",
        level=2,
        business_description="Represents region, coarse geography dimension",
        aliases=["区域", "Region", "大区"],
        reasoning="Geography dimension coarse level, represents region",
    ),
    DimensionSeed(
        field_caption="大区",
        data_type="string",
        category="geography",
        category_detail="geography-region",
        level=1,
        business_description="表示大区，地理维度最粗粒度",
        aliases=["区域", "Region", "地区"],
        reasoning="地理维度最粗粒度，表示大区",
    ),
    DimensionSeed(
        field_caption="postal_code",
        data_type="string",
        category="geography",
        category_detail="geography-postal",
        level=5,
        business_description="Postal code for mail delivery",
        aliases=["邮编", "Postal Code", "邮政编码"],
        reasoning="Postal code, geography dimension finest level",
    ),
    DimensionSeed(
        field_caption="zip_code",
        data_type="string",
        category="geography",
        category_detail="geography-postal",
        level=5,
        business_description="ZIP code for mail delivery",
        aliases=["邮编", "ZIP Code", "邮政编码"],
        reasoning="Zip code, geography dimension finest level",
    ),
    DimensionSeed(
        field_caption="address",
        data_type="string",
        category="geography",
        category_detail="geography-address",
        level=5,
        business_description="Full address for delivery",
        aliases=["地址", "Address", "详细地址"],
        reasoning="Address, geography dimension finest level",
    ),
]
