# -*- coding: utf-8 -*-
"""组织维度种子数据（部门、团队、员工等）"""
from ._types import DimensionSeed

_ORGANIZATION_SEEDS: list[DimensionSeed] = [
    DimensionSeed(
        field_caption="公司名称",
        data_type="string",
        category="organization",
        category_detail="organization-company",
        level=1,
        business_description="表示公司名称，组织维度最粗粒度",
        aliases=["公司", "Company Name", "企业名称"],
        reasoning="组织维度最粗粒度，表示公司",
    ),
    DimensionSeed(
        field_caption="公司",
        data_type="string",
        category="organization",
        category_detail="organization-company",
        level=1,
        business_description="表示公司，组织维度最粗粒度",
        aliases=["公司名称", "Company", "企业"],
        reasoning="组织维度最粗粒度，表示公司",
    ),
    DimensionSeed(
        field_caption="company",
        data_type="string",
        category="organization",
        category_detail="organization-company",
        level=1,
        business_description="Company, coarsest organization dimension",
        aliases=["公司", "Company", "企业"],
        reasoning="Organization dimension coarsest level, represents company",
    ),
    DimensionSeed(
        field_caption="company_name",
        data_type="string",
        category="organization",
        category_detail="organization-company",
        level=1,
        business_description="Company name for identification",
        aliases=["公司名称", "Company", "企业名称"],
        reasoning="Company name, organization dimension coarsest level",
    ),
    DimensionSeed(
        field_caption="部门",
        data_type="string",
        category="organization",
        category_detail="organization-department",
        level=2,
        business_description="表示部门，组织维度粗粒度",
        aliases=["部门名称", "Department", "科室"],
        reasoning="组织维度粗粒度，表示部门",
    ),
    DimensionSeed(
        field_caption="saleper_company",
        data_type="string",
        category="organization",
        category_detail="organization-department",
        level=2,
        business_description="Sales department or company",
        aliases=["销售公司", "Sales Company", "销售部门"],
        reasoning="Sales department, organization dimension coarse level",
    ),
    DimensionSeed(
        field_caption="department",
        data_type="string",
        category="organization",
        category_detail="organization-department",
        level=2,
        business_description="Department, coarse organization dimension",
        aliases=["部门", "Department", "科室"],
        reasoning="Organization dimension coarse level, represents department",
    ),
    DimensionSeed(
        field_caption="团队",
        data_type="string",
        category="organization",
        category_detail="organization-team",
        level=3,
        business_description="表示团队，组织维度中等粒度",
        aliases=["团队名称", "Team", "小组"],
        reasoning="组织维度中等粒度，表示团队",
    ),
    DimensionSeed(
        field_caption="team",
        data_type="string",
        category="organization",
        category_detail="organization-team",
        level=3,
        business_description="Team, medium organization dimension",
        aliases=["团队", "Team", "小组"],
        reasoning="Organization dimension medium level, represents team",
    ),
    DimensionSeed(
        field_caption="员工",
        data_type="string",
        category="organization",
        category_detail="organization-employee",
        level=5,
        business_description="表示员工，组织维度最细粒度",
        aliases=["员工姓名", "Employee", "职员"],
        reasoning="组织维度最细粒度，表示员工",
    ),
    DimensionSeed(
        field_caption="员工姓名",
        data_type="string",
        category="organization",
        category_detail="organization-employee",
        level=5,
        business_description="表示员工姓名，组织维度最细粒度",
        aliases=["员工", "Employee Name", "姓名"],
        reasoning="组织维度最细粒度，表示员工姓名",
    ),
    DimensionSeed(
        field_caption="销售员",
        data_type="string",
        category="organization",
        category_detail="organization-employee",
        level=5,
        business_description="销售员，组织维度最细粒度",
        aliases=["销售人员", "Salesperson", "业务员"],
        reasoning="销售员，组织维度最细粒度",
    ),
    DimensionSeed(
        field_caption="employee",
        data_type="string",
        category="organization",
        category_detail="organization-employee",
        level=5,
        business_description="Employee, finest organization dimension",
        aliases=["员工", "Employee", "职员"],
        reasoning="Organization dimension finest level, represents employee",
    ),
    DimensionSeed(
        field_caption="employee_name",
        data_type="string",
        category="organization",
        category_detail="organization-employee",
        level=5,
        business_description="Employee name for identification",
        aliases=["员工姓名", "Employee", "姓名"],
        reasoning="Employee name, organization dimension finest level",
    ),
    DimensionSeed(
        field_caption="employee_id",
        data_type="string",
        category="organization",
        category_detail="organization-employee",
        level=5,
        business_description="Employee unique identifier",
        aliases=["员工ID", "Employee ID", "员工编号"],
        reasoning="Employee ID, organization dimension finest level",
    ),
    DimensionSeed(
        field_caption="sales_rep",
        data_type="string",
        category="organization",
        category_detail="organization-employee",
        level=5,
        business_description="Sales representative name",
        aliases=["销售代表", "Sales Rep", "销售员"],
        reasoning="Sales representative, organization dimension finest level",
    ),
    DimensionSeed(
        field_caption="salesperson",
        data_type="string",
        category="organization",
        category_detail="organization-employee",
        level=5,
        business_description="Salesperson name",
        aliases=["销售员", "Salesperson", "业务员"],
        reasoning="Salesperson, organization dimension finest level",
    ),
    DimensionSeed(
        field_caption="division",
        data_type="string",
        category="organization",
        category_detail="organization-division",
        level=2,
        business_description="Division, coarse organization dimension",
        aliases=["事业部", "Division", "分部"],
        reasoning="Division, organization dimension coarse level",
    ),
    DimensionSeed(
        field_caption="经理",
        data_type="string",
        category="organization",
        category_detail="organization-manager",
        level=3,
        business_description="管理人员",
        aliases=["manager", "Manager", "主管", "负责人"],
        reasoning="经理，组织维度中等粒度",
    ),
    DimensionSeed(
        field_caption="经理姓名",
        data_type="string",
        category="organization",
        category_detail="organization-manager",
        level=3,
        business_description="管理人员姓名",
        aliases=["manager_name", "Manager Name", "主管姓名"],
        reasoning="经理姓名，组织维度中等粒度",
    ),
    DimensionSeed(
        field_caption="manager",
        data_type="string",
        category="organization",
        category_detail="organization-manager",
        level=3,
        business_description="Manager or supervisor",
        aliases=["Manager", "经理", "主管"],
        reasoning="Manager, organization dimension medium level",
    ),
    DimensionSeed(
        field_caption="manager_name",
        data_type="string",
        category="organization",
        category_detail="organization-manager",
        level=3,
        business_description="Manager name",
        aliases=["Manager Name", "经理姓名", "主管姓名"],
        reasoning="Manager name, organization dimension medium level",
    ),
    DimensionSeed(
        field_caption="manager_id",
        data_type="string",
        category="organization",
        category_detail="organization-manager",
        level=3,
        business_description="Manager unique identifier",
        aliases=["Manager ID", "经理ID"],
        reasoning="Manager ID, organization dimension medium level",
    ),
]
