# -*- coding: utf-8 -*-
"""产品维度种子数据（类别、子类、品牌、SKU 等）"""
from ._types import DimensionSeed

_PRODUCT_SEEDS: list[DimensionSeed] = [
    DimensionSeed(
        field_caption="产品类别",
        data_type="string",
        category="product",
        category_detail="product-category",
        level=1,
        business_description="表示产品大类，产品维度最粗粒度",
        aliases=["产品大类", "Category", "类别"],
        reasoning="产品维度最粗粒度，表示产品大类",
    ),
    DimensionSeed(
        field_caption="category",
        data_type="string",
        category="product",
        category_detail="product-category",
        level=1,
        business_description="Product category, coarsest product dimension",
        aliases=["产品类别", "Category", "类别"],
        reasoning="Product dimension coarsest level, represents category",
    ),
    DimensionSeed(
        field_caption="product_category",
        data_type="string",
        category="product",
        category_detail="product-category",
        level=1,
        business_description="Product category for classification",
        aliases=["产品类别", "Category", "产品分类"],
        reasoning="Product category, product dimension coarsest level",
    ),
    DimensionSeed(
        field_caption="事业线名称",
        data_type="string",
        category="product",
        category_detail="product-business-line",
        level=1,
        business_description="表示事业线，产品维度最粗粒度",
        aliases=["事业线", "Business Line", "业务线"],
        reasoning="产品维度最粗粒度，表示事业线",
    ),
    DimensionSeed(
        field_caption="产品子类",
        data_type="string",
        category="product",
        category_detail="product-subcategory",
        level=2,
        business_description="表示产品子类，产品维度粗粒度",
        aliases=["子类", "Subcategory", "产品分类"],
        reasoning="产品维度粗粒度，表示产品子类",
    ),
    DimensionSeed(
        field_caption="subcategory",
        data_type="string",
        category="product",
        category_detail="product-subcategory",
        level=2,
        business_description="Product subcategory, coarse product dimension",
        aliases=["产品子类", "Subcategory", "子类"],
        reasoning="Product dimension coarse level, represents subcategory",
    ),
    DimensionSeed(
        field_caption="Sub-Category",
        data_type="string",
        category="product",
        category_detail="product-subcategory",
        level=2,
        business_description="Product subcategory, coarse product dimension",
        aliases=["产品子类", "subcategory", "子类"],
        reasoning="Product dimension coarse level, represents subcategory",
    ),
    DimensionSeed(
        field_caption="product_subcategory",
        data_type="string",
        category="product",
        category_detail="product-subcategory",
        level=2,
        business_description="Product subcategory for classification",
        aliases=["产品子类", "Subcategory", "子分类"],
        reasoning="Product subcategory, product dimension coarse level",
    ),
    DimensionSeed(
        field_caption="子类别",
        data_type="string",
        category="product",
        category_detail="product-subcategory",
        level=2,
        business_description="产品的子分类",
        aliases=["Sub-Category", "subcategory", "子类", "二级分类"],
        reasoning="子类别，产品维度粗粒度",
    ),
    DimensionSeed(
        field_caption="品牌",
        data_type="string",
        category="product",
        category_detail="product-brand",
        level=3,
        business_description="表示品牌，产品维度中等粒度",
        aliases=["品牌名称", "Brand", "商标"],
        reasoning="产品维度中等粒度，表示品牌",
    ),
    DimensionSeed(
        field_caption="brand",
        data_type="string",
        category="product",
        category_detail="product-brand",
        level=3,
        business_description="Product brand, medium product dimension",
        aliases=["品牌", "Brand", "商标"],
        reasoning="Product dimension medium level, represents brand",
    ),
    DimensionSeed(
        field_caption="brand_name",
        data_type="string",
        category="product",
        category_detail="product-brand",
        level=3,
        business_description="Brand name for display",
        aliases=["品牌名称", "Brand", "品牌"],
        reasoning="Brand name, product dimension medium level",
    ),
    DimensionSeed(
        field_caption="产品名称",
        data_type="string",
        category="product",
        category_detail="product-name",
        level=4,
        business_description="表示产品名称，产品维度细粒度",
        aliases=["产品", "Product Name", "商品名称"],
        reasoning="产品维度细粒度，表示产品名称",
    ),
    DimensionSeed(
        field_caption="物料名称",
        data_type="string",
        category="product",
        category_detail="product-name",
        level=4,
        business_description="物料名称，产品维度细粒度",
        aliases=["物料", "Material Name", "材料名称"],
        reasoning="物料名称，产品维度细粒度",
    ),
    DimensionSeed(
        field_caption="product_name",
        data_type="string",
        category="product",
        category_detail="product-name",
        level=4,
        business_description="Product name for identification",
        aliases=["产品名称", "Product", "商品名称"],
        reasoning="Product name, product dimension fine level",
    ),
    DimensionSeed(
        field_caption="Product Name",
        data_type="string",
        category="product",
        category_detail="product-name",
        level=4,
        business_description="Product name for identification",
        aliases=["产品名称", "product_name", "商品名称"],
        reasoning="Product name, product dimension fine level",
    ),
    DimensionSeed(
        field_caption="material_name",
        data_type="string",
        category="product",
        category_detail="product-name",
        level=4,
        business_description="Material name for identification",
        aliases=["物料名称", "Material", "材料名称"],
        reasoning="Material name, product dimension fine level",
    ),
    DimensionSeed(
        field_caption="物料编码",
        data_type="string",
        category="product",
        category_detail="product-sku",
        level=5,
        business_description="物料编码，产品维度最细粒度",
        aliases=["物料号", "Material Code", "物料ID"],
        reasoning="物料编码，产品维度最细粒度",
    ),
    DimensionSeed(
        field_caption="SKU",
        data_type="string",
        category="product",
        category_detail="product-sku",
        level=5,
        business_description="SKU编码，产品维度最细粒度",
        aliases=["SKU编码", "Stock Keeping Unit", "库存单位"],
        reasoning="SKU编码，产品维度最细粒度",
    ),
    DimensionSeed(
        field_caption="product_id",
        data_type="string",
        category="product",
        category_detail="product-sku",
        level=5,
        business_description="Product unique identifier",
        aliases=["产品ID", "Product ID", "产品编码"],
        reasoning="Product ID, product dimension finest level",
    ),
    DimensionSeed(
        field_caption="Product ID",
        data_type="string",
        category="product",
        category_detail="product-sku",
        level=5,
        business_description="Product unique identifier",
        aliases=["产品ID", "product_id", "产品编码"],
        reasoning="Product ID, product dimension finest level",
    ),
    DimensionSeed(
        field_caption="material",
        data_type="string",
        category="product",
        category_detail="product-sku",
        level=5,
        business_description="Material code for inventory",
        aliases=["物料", "Material Code", "物料编码"],
        reasoning="Material code, product dimension finest level",
    ),
    DimensionSeed(
        field_caption="item_id",
        data_type="string",
        category="product",
        category_detail="product-sku",
        level=5,
        business_description="Item unique identifier",
        aliases=["商品ID", "Item ID", "商品编码"],
        reasoning="Item ID, product dimension finest level",
    ),
]
