# -*- coding: utf-8 -*-
"""时间维度种子数据（年、季度、月、周、日等）"""
from ._types import DimensionSeed

_TIME_SEEDS: list[DimensionSeed] = [
    DimensionSeed(
        field_caption="年",
        data_type="integer",
        category="time",
        category_detail="time-year",
        level=1,
        business_description="表示年份，时间维度最粗粒度",
        aliases=["年份", "Year", "财年"],
        reasoning="时间维度最粗粒度，表示年份",
    ),
    DimensionSeed(
        field_caption="年份",
        data_type="integer",
        category="time",
        category_detail="time-year",
        level=1,
        business_description="表示年份，时间维度最粗粒度",
        aliases=["年", "Year", "财年"],
        reasoning="时间维度最粗粒度，表示年份",
    ),
    DimensionSeed(
        field_caption="year",
        data_type="integer",
        category="time",
        category_detail="time-year",
        level=1,
        business_description="Represents year, coarsest time dimension",
        aliases=["年", "Year", "fiscal_year"],
        reasoning="Time dimension coarsest level, represents year",
    ),
    DimensionSeed(
        field_caption="fiscal_year",
        data_type="integer",
        category="time",
        category_detail="time-year",
        level=1,
        business_description="Fiscal year for financial reporting",
        aliases=["财年", "Year", "FY"],
        reasoning="Fiscal year, time dimension coarsest level",
    ),
    DimensionSeed(
        field_caption="季度",
        data_type="string",
        category="time",
        category_detail="time-quarter",
        level=2,
        business_description="表示季度，时间维度粗粒度",
        aliases=["季", "Quarter", "Q"],
        reasoning="时间维度粗粒度，表示季度",
    ),
    DimensionSeed(
        field_caption="quarter",
        data_type="string",
        category="time",
        category_detail="time-quarter",
        level=2,
        business_description="Represents quarter, coarse time dimension",
        aliases=["季度", "Quarter", "Q"],
        reasoning="Time dimension coarse level, represents quarter",
    ),
    DimensionSeed(
        field_caption="月",
        data_type="integer",
        category="time",
        category_detail="time-month",
        level=3,
        business_description="表示月份，时间维度中等粒度",
        aliases=["月份", "Month", "月度"],
        reasoning="时间维度中等粒度，表示月份",
    ),
    DimensionSeed(
        field_caption="月份",
        data_type="integer",
        category="time",
        category_detail="time-month",
        level=3,
        business_description="表示月份，时间维度中等粒度",
        aliases=["月", "Month", "月度"],
        reasoning="时间维度中等粒度，表示月份",
    ),
    DimensionSeed(
        field_caption="month",
        data_type="integer",
        category="time",
        category_detail="time-month",
        level=3,
        business_description="Represents month, medium time dimension",
        aliases=["月份", "Month", "月"],
        reasoning="Time dimension medium level, represents month",
    ),
    DimensionSeed(
        field_caption="周",
        data_type="integer",
        category="time",
        category_detail="time-week",
        level=4,
        business_description="表示周，时间维度细粒度",
        aliases=["周次", "Week", "星期"],
        reasoning="时间维度细粒度，表示周",
    ),
    DimensionSeed(
        field_caption="week",
        data_type="integer",
        category="time",
        category_detail="time-week",
        level=4,
        business_description="Represents week number, fine time dimension",
        aliases=["周", "Week", "周次"],
        reasoning="Time dimension fine level, represents week",
    ),
    DimensionSeed(
        field_caption="week_number",
        data_type="integer",
        category="time",
        category_detail="time-week",
        level=4,
        business_description="Week number within year",
        aliases=["周次", "Week", "周"],
        reasoning="Week number, time dimension fine level",
    ),
    DimensionSeed(
        field_caption="日期",
        data_type="date",
        category="time",
        category_detail="time-date",
        level=5,
        business_description="表示具体日期，时间维度最细粒度",
        aliases=["日", "Date", "天"],
        reasoning="时间维度最细粒度，表示日期",
    ),
    DimensionSeed(
        field_caption="date",
        data_type="date",
        category="time",
        category_detail="time-date",
        level=5,
        business_description="Represents specific date, finest time dimension",
        aliases=["日期", "Date", "日"],
        reasoning="Time dimension finest level, represents date",
    ),
    DimensionSeed(
        field_caption="order_date",
        data_type="date",
        category="time",
        category_detail="time-date",
        level=5,
        business_description="Date when order was placed",
        aliases=["订单日期", "Order Date", "下单日期"],
        reasoning="Order date, time dimension finest level",
    ),
    DimensionSeed(
        field_caption="ship_date",
        data_type="date",
        category="time",
        category_detail="time-date",
        level=5,
        business_description="Date when order was shipped",
        aliases=["发货日期", "Ship Date", "出货日期"],
        reasoning="Ship date, time dimension finest level",
    ),
    DimensionSeed(
        field_caption="create_date",
        data_type="date",
        category="time",
        category_detail="time-date",
        level=5,
        business_description="Date when record was created",
        aliases=["创建日期", "Create Date", "创建时间"],
        reasoning="Create date, time dimension finest level",
    ),
    DimensionSeed(
        field_caption="日",
        data_type="integer",
        category="time",
        category_detail="time-day",
        level=5,
        business_description="表示日，时间维度最细粒度",
        aliases=["日期", "Day", "天"],
        reasoning="时间维度最细粒度，表示日",
    ),
    DimensionSeed(
        field_caption="day",
        data_type="integer",
        category="time",
        category_detail="time-day",
        level=5,
        business_description="Day of month",
        aliases=["日", "Day", "天"],
        reasoning="Day of month, time dimension finest level",
    ),
    DimensionSeed(
        field_caption="month_name",
        data_type="string",
        category="time",
        category_detail="time-month",
        level=3,
        business_description="Month name for display",
        aliases=["月份名称", "Month Name", "月名"],
        reasoning="Month name, time dimension medium level",
    ),
    DimensionSeed(
        field_caption="day_of_week",
        data_type="string",
        category="time",
        category_detail="time-day",
        level=5,
        business_description="Day of week name",
        aliases=["星期", "Weekday", "周几"],
        reasoning="Day of week, time dimension finest level",
    ),
]
