"""ReAct Error Handler - LLM-based error analysis for QueryPipeline.

When QueryPipeline encounters an error, this handler uses LLM to:
1. Analyze the error and identify root cause (Thought)
2. Decide on action: RETRY (from which step), CLARIFY, or ABORT (Action)
3. Generate appropriate feedback/message

Key Design:
- LLM identifies which step caused the error
- RETRY goes back to the problematic step with error feedback
- All user-facing messages are generated by LLM

Uses call_llm_with_tools pattern (same as step1.py):
- call_llm_with_tools(): supports tool calls + middleware + streaming
- parse_json_response(): parses JSON response
- Does not use with_structured_output (not supported by DeepSeek R1)
"""

import logging
from typing import Any, Dict, List, Optional

from langchain_core.language_models import BaseChatModel
from langgraph.types import RunnableConfig

from ..models.pipeline import QueryError, QueryResult
from ..models.react import (
    ReActThought,
    ReActAction,
    ReActActionType,
    ReActObservation,
    ReActOutput,
    RetryTarget,
)
from ..prompts.react_error import REACT_ERROR_PROMPT
from tableau_assistant.src.agents.base import (
    get_llm,
    call_llm_with_tools,
    parse_json_response,
)

logger = logging.getLogger(__name__)


class ReActErrorHandler:
    """LLM-based error handler for QueryPipeline errors.
    
    This handler uses LLM to:
    1. Analyze error and identify root cause
    2. Decide which step to retry from (or CLARIFY/ABORT)
    3. Generate error feedback for retry, or user message for abort
    
    Attributes:
        llm: Language model for error analysis
        max_retries_per_step: Maximum retries for each step
    """
    
    def __init__(
        self,
        llm: Optional[BaseChatModel] = None,
        max_retries_per_step: int = 2,
    ):
        """Initialize ReAct error handler.
        
        Args:
            llm: Language model for error analysis (uses default if None)
            max_retries_per_step: Maximum retries per step (default: 2)
        """
        self._llm = llm
        self.max_retries_per_step = max_retries_per_step
    
    @property
    def llm(self) -> BaseChatModel:
        """Get LLM instance (lazy initialization)."""
        if self._llm is None:
            self._llm = get_llm(agent_name="semantic_parser")
        return self._llm
    
    async def handle_error(
        self,
        error: QueryError,
        question: str,
        pipeline_context: Optional[Dict[str, Any]] = None,
        retry_history: Optional[List[ReActObservation]] = None,
        config: Optional[RunnableConfig] = None,
    ) -> ReActOutput:
        """Handle a QueryPipeline error using LLM.
        
        Args:
            error: QueryError from pipeline
            question: Original user question
            pipeline_context: Context from pipeline execution (step1_output, step2_output, etc.)
            retry_history: History of previous retry attempts
            config: LangGraph config
        
        Returns:
            ReActOutput with LLM-generated thought and action
        """
        retry_history = retry_history or []
        pipeline_context = pipeline_context or {}
        
        # Check if max retries reached for this step
        step_retry_count = self._count_retries_for_step(retry_history, error.step)
        if step_retry_count >= self.max_retries_per_step:
            logger.info(f"Max retries ({self.max_retries_per_step}) reached for step {error.step}")
            return self._create_max_retry_output(error, error.step)
        
        # Call LLM to analyze error
        try:
            output = await self._call_llm_for_analysis(
                error=error,
                question=question,
                pipeline_context=pipeline_context,
                retry_history=retry_history,
                config=config,
            )
            
            logger.info(
                f"ReAct decision: action={output.action.action_type}, "
                f"retry_from={output.action.retry_from}, "
                f"root_cause={output.thought.root_cause}"
            )
            
            return output
            
        except Exception as e:
            logger.error(f"LLM error analysis failed: {e}", exc_info=True)
            return self._create_fallback_output(error)
    
    async def _call_llm_for_analysis(
        self,
        error: QueryError,
        question: str,
        pipeline_context: Dict[str, Any],
        retry_history: List[ReActObservation],
        config: Optional[RunnableConfig],
    ) -> ReActOutput:
        """Call LLM to analyze error and generate response.
        
        Uses call_llm_with_tools + parse_json_response pattern
        (same as step1.py) for compatibility with DeepSeek R1 model.
        """
        # Format pipeline context
        context_str = self._format_pipeline_context(pipeline_context)
        
        # Format retry history
        history_str = self._format_retry_history(retry_history)
        
        # Format error details
        error_details = "None"
        if error.details:
            error_details = "\n".join(f"  - {k}: {v}" for k, v in error.details.items())
        if error.suggestion:
            error_details += f"\n  - Suggestion: {error.suggestion}"
        
        # Build prompt using format_messages
        messages = REACT_ERROR_PROMPT.format_messages(
            question=question,
            pipeline_context=context_str,
            error_step=error.step,
            error_type=error.type.value,
            error_message=error.message,
            error_details=error_details,
            retry_history=history_str or "无重试历史",
        )
        
        # Get middleware from config
        middleware = None
        if config and "configurable" in config:
            middleware = config["configurable"].get("middleware")
        
        # Call LLM using call_llm_with_tools (same pattern as step1.py)
        response = await call_llm_with_tools(
            llm=self.llm,
            messages=messages,
            tools=[],
            streaming=True,
            middleware=middleware,
            state={},
            config=config,
        )
        
        # Parse JSON response into ReActOutput
        try:
            result = parse_json_response(response.content, ReActOutput)
            return result
        except ValueError as e:
            logger.warning(f"Failed to parse ReAct output: {e}")
            return self._create_fallback_output(error)
    
    def _format_pipeline_context(self, context: Dict[str, Any]) -> str:
        """Format pipeline context for prompt."""
        if not context:
            return "无上下文信息"
        
        lines = []
        
        if "step1_output" in context and context["step1_output"]:
            step1 = context["step1_output"]
            lines.append("### Step1 输出:")
            lines.append(f"  - 意图: {getattr(step1, 'intent', 'N/A')}")
            lines.append(f"  - 重述问题: {getattr(step1, 'restated_question', 'N/A')}")
            if hasattr(step1, 'what') and step1.what:
                lines.append(f"  - What: {step1.what}")
            if hasattr(step1, 'where') and step1.where:
                lines.append(f"  - Where: {step1.where}")
        
        if "step2_output" in context and context["step2_output"]:
            step2 = context["step2_output"]
            lines.append("### Step2 输出:")
            if hasattr(step2, 'computations') and step2.computations:
                lines.append(f"  - 计算: {step2.computations}")
        
        if "semantic_query" in context and context["semantic_query"]:
            lines.append("### SemanticQuery:")
            lines.append(f"  {context['semantic_query']}")
        
        if "mapped_query" in context and context["mapped_query"]:
            lines.append("### MappedQuery:")
            lines.append(f"  {context['mapped_query']}")
        
        if "vizql_query" in context and context["vizql_query"]:
            lines.append("### VizQL Query:")
            lines.append(f"  {context['vizql_query']}")
        
        return "\n".join(lines) if lines else "无上下文信息"
    
    def _format_retry_history(self, history: List[ReActObservation]) -> str:
        """Format retry history for prompt."""
        if not history:
            return ""
        
        lines = []
        for i, obs in enumerate(history, 1):
            status = "✓" if obs.success else "✗"
            lines.append(f"{i}. [{status}] {obs.step}: {obs.error_message or 'Success'}")
        return "\n".join(lines)
    
    def _count_retries_for_step(self, history: List[ReActObservation], step: str) -> int:
        """Count how many times a step has been retried."""
        return sum(1 for obs in history if obs.step == step and not obs.success)
    
    def _create_max_retry_output(self, error: QueryError, step: str) -> ReActOutput:
        """Create output when max retries reached."""
        thought = ReActThought(
            error_analysis=f"步骤 {step} 已达到最大重试次数",
            root_cause=step,
            can_retry=False,
            needs_clarification=False,
            reasoning=f"已尝试 {self.max_retries_per_step} 次仍然失败，无法继续重试",
        )
        
        action = ReActAction(
            action_type=ReActActionType.ABORT,
            user_message=f"抱歉，处理您的请求时遇到问题：{error.message}。请尝试换一种方式描述您的问题，或者简化您的查询条件。",
        )
        
        return ReActOutput(thought=thought, action=action)
    
    def _create_fallback_output(self, error: QueryError) -> ReActOutput:
        """Create fallback output when LLM fails."""
        thought = ReActThought(
            error_analysis=f"错误分析失败。原始错误: {error.message}",
            root_cause=error.step,
            can_retry=False,
            needs_clarification=False,
            reasoning="无法分析错误，返回原始错误信息",
        )
        
        action = ReActAction(
            action_type=ReActActionType.ABORT,
            user_message=f"抱歉，处理您的请求时遇到问题。{error.message}",
        )
        
        return ReActOutput(thought=thought, action=action)
    
    def create_observation(
        self,
        step: str,
        error: Optional[QueryError] = None,
        result: Optional[Any] = None,
    ) -> ReActObservation:
        """Create observation from step execution result.
        
        Args:
            step: Which step produced this result
            error: QueryError if failed
            result: Result if succeeded
        
        Returns:
            ReActObservation
        """
        if error:
            return ReActObservation(
                success=False,
                step=step,
                error_type=error.type.value,
                error_message=error.message,
                error_details=error.details,
            )
        else:
            return ReActObservation(
                success=True,
                step=step,
                result=result,
            )


__all__ = ["ReActErrorHandler"]
