# -*- coding: utf-8 -*-
"""Replan Models.

Data models for replanning.

Following PROMPT_AND_MODEL_GUIDE.md specification:
- Use XML tags for field descriptions (<what>, <when>, <how>, <values>, <decision_rule>, <examples>, <anti_patterns>)
- Class docstring contains <fill_order>, <examples>, <anti_patterns>
- Use ConfigDict(extra="forbid") to prevent extra fields

Contains:
- ExplorationQuestion: Exploration question
- ReplanDecision: Replan decision
"""
from typing import List, Optional, Literal
from pydantic import BaseModel, Field, ConfigDict


class ExplorationQuestion(BaseModel):
    """Exploration question - Generated by Replanner LLM.
    
    <what>Single exploration question with text, type, target dimension and priority</what>
    
    <fill_order>
    1. question (ALWAYS)
    2. exploration_type (ALWAYS)
    3. target_dimension (ALWAYS)
    4. priority (ALWAYS)
    5. reasoning (ALWAYS)
    6. filter (optional)
    </fill_order>
    
    <examples>
    drill_down: {"question": "What is Store A's sales distribution by product category?", "exploration_type": "drill_down", "target_dimension": "Product Category", "priority": 0.8}
    time_series: {"question": "What is Store A's sales trend over the last 12 months?", "exploration_type": "time_series", "target_dimension": "Month", "priority": 0.9}
    </examples>
    
    <anti_patterns>
    X Using template placeholders: {"question": "{entity}'s sales"}
    X Repeating already answered questions
    X Using target_dimension not in dimension_hierarchy
    </anti_patterns>
    """
    model_config = ConfigDict(extra="forbid")
    
    question: str = Field(
        description="""<what>Exploration question text (generated by LLM)</what>

<when>ALWAYS required</when>

<how>Use specific entity names from insights, in user's language</how>

<decision_rule>
- Extract entity names from current insights
- Formulate question targeting ONE specific dimension
- Use user's language (from user_language parameter)
</decision_rule>

<anti_patterns>
X Use {entity} or similar placeholders
X Use technical field names instead of business terms
</anti_patterns>"""
    )
    
    exploration_type: Literal[
        "drill_down",
        "roll_up",
        "time_series",
        "peer_comparison",
        "cross_dimension",
        "anomaly_investigation",
        "correlation_analysis"
    ] = Field(
        description="""<what>Type of exploration to perform</what>

<when>ALWAYS required</when>

<how>Select based on identified gap and dimension hierarchy</how>

<values>
- drill_down: Need finer granularity (category → subcategory)
- roll_up: Need coarser granularity (subcategory → category)
- time_series: Need temporal analysis (monthly/quarterly/yearly trends)
- peer_comparison: Need horizontal comparison (A vs B vs C)
- cross_dimension: Need multi-dimensional analysis (analyze from different angle)
- anomaly_investigation: Found anomaly, need to investigate cause
- correlation_analysis: Need to analyze relationships between variables
</values>

<decision_rule>
IF user asks "why" → prefer drill_down or anomaly_investigation
IF user asks "trend" → prefer time_series
IF user asks "compare" → prefer peer_comparison
IF only one dimension analyzed → consider cross_dimension
IF anomaly found → prefer anomaly_investigation
</decision_rule>"""
    )
    
    target_dimension: str = Field(
        description="""<what>Target dimension for exploration</what>

<when>ALWAYS required</when>

<how>Select from dimension_hierarchy keys</how>

<dependency>
- field: dimension_hierarchy
- condition: must be a key in dimension_hierarchy
- reason: ensures valid dimension for exploration
</dependency>

<decision_rule>
- For drill_down: select child dimension (finer level)
- For roll_up: select parent dimension (coarser level)
- For time_series: select time dimension
- For cross_dimension: select unexplored dimension
</decision_rule>

<anti_patterns>
X Use arbitrary text not in dimension_hierarchy
X Use technical field names instead of business terms
</anti_patterns>"""
    )
    
    filter: Optional[str] = Field(
        default=None,
        description="""<what>Filter condition for scoped analysis</what>

<when>When scope restriction needed</when>

<how>Natural language filter expression</how>"""
    )
    
    priority: float = Field(
        ge=0.0,
        le=1.0,
        description="""<what>Priority score for this question</what>

<when>ALWAYS required</when>

<how>Float between 0 and 1</how>

<values>
- 0.9-1.0: Directly answers user's question
- 0.7-0.9: Key supporting information
- 0.4-0.7: Deepens understanding
- 0.0-0.4: Peripheral exploration
</values>

<decision_rule>
Higher priority for questions that:
- Directly address user's original question
- Fill critical gaps in current insights
- Target dimensions mentioned by user
</decision_rule>"""
    )
    
    reasoning: str = Field(
        description="""<what>Reasoning for generating this question</what>

<when>ALWAYS required</when>

<how>Explain why this question was generated and how it fills a gap</how>"""
    )


class ReplanDecision(BaseModel):
    """Replan decision - Supports parallel multi-question execution.
    
    <what>Replan decision with completeness assessment and exploration question list</what>
    
    <fill_order>
    1. completeness_score (ALWAYS first - determines other fields)
    2. should_replan (ALWAYS - derived from completeness_score)
    3. reason (ALWAYS)
    4. missing_aspects (if should_replan=True)
    5. exploration_questions (if should_replan=True)
    6. confidence (ALWAYS)
    </fill_order>
    
    <decision_tree>
    START
      │
      ├─► completeness_score = ? (ALWAYS fill first)
      │   │
      │   ├─► >= 0.9 → should_replan = false, skip exploration_questions
      │   │
      │   └─► < 0.9 → should_replan = true
      │       │
      │       ├─► fill missing_aspects (required)
      │       │
      │       └─► fill exploration_questions (required, 1-5 questions)
      │
      ├─► reason = ? (ALWAYS fill)
      │
      └─► confidence = ? (ALWAYS fill)
      
    END
    </decision_tree>
    
    <examples>
    Complete: {"completeness_score": 0.95, "should_replan": false, "reason": "Core question fully answered", "missing_aspects": [], "exploration_questions": [], "confidence": 0.9}
    Needs replan: {"completeness_score": 0.6, "should_replan": true, "reason": "Missing time trend analysis", "missing_aspects": ["time trend"], "exploration_questions": [...], "confidence": 0.8}
    </examples>
    
    <anti_patterns>
    X completeness_score < 0.9 but should_replan = false
    X should_replan = true but exploration_questions is empty
    X exploration_questions contains repeated questions from answered_questions
    </anti_patterns>
    """
    model_config = ConfigDict(extra="forbid")
    
    completeness_score: float = Field(
        ge=0.0,
        le=1.0,
        description="""<what>Analysis completeness score</what>

<when>ALWAYS required (fill first)</when>

<how>Float between 0 and 1</how>

<values>
- >= 0.9: Fully answered, no replan needed
- 0.7-0.9: Mostly answered, minor gaps
- < 0.7: Needs replan, significant gaps
</values>

<decision_rule>
Assess based on:
- Does insight directly answer user's question?
- Are all aspects addressed?
- Is there enough detail to understand "why"?
</decision_rule>"""
    )
    
    should_replan: bool = Field(
        description="""<what>Whether replan is needed</what>

<when>ALWAYS required</when>

<how>Boolean derived from completeness_score</how>

<dependency>
- field: completeness_score
- condition: completeness_score < 0.9 → true
- reason: Low completeness requires more exploration
</dependency>

<decision_rule>
IF completeness_score >= 0.9 THEN false
IF completeness_score < 0.9 THEN true
</decision_rule>

<anti_patterns>
X completeness_score < 0.9 but should_replan = false
</anti_patterns>"""
    )
    
    reason: str = Field(
        description="""<what>Assessment reason</what>

<when>ALWAYS required</when>

<how>Explain why replan is/isn't needed</how>"""
    )
    
    missing_aspects: List[str] = Field(
        default_factory=list,
        description="""<what>Missing analysis aspects</what>

<when>Required when should_replan=True</when>

<how>List of gaps identified in current insights</how>

<dependency>
- field: should_replan
- condition: should_replan == True
- reason: Only need to list gaps when replanning
</dependency>"""
    )
    
    exploration_questions: List[ExplorationQuestion] = Field(
        default_factory=list,
        description="""<what>Exploration question list</what>

<when>Required when should_replan=True</when>

<how>List of ExplorationQuestion objects, max 5, sorted by priority</how>

<dependency>
- field: should_replan
- condition: should_replan == True
- reason: Only generate questions when replanning
</dependency>

<decision_rule>
- Generate 1-5 questions based on missing_aspects
- Each question targets ONE dimension from dimension_hierarchy
- Sort by priority (highest first)
- Check answered_questions to avoid duplicates
</decision_rule>

<anti_patterns>
X Empty list when should_replan = true
X More than 5 questions
X Questions repeating answered_questions
</anti_patterns>"""
    )
    
    parallel_execution: bool = Field(
        default=True,
        description="""<what>Whether to execute questions in parallel</what>

<when>Default True</when>

<how>Boolean flag</how>"""
    )
    
    max_questions_per_round: int = Field(
        default=3,
        ge=1,
        le=5,
        description="""<what>Max questions to execute per round</what>

<when>Default 3</when>

<how>Integer between 1 and 5</how>"""
    )
    
    confidence: float = Field(
        default=0.8,
        ge=0.0,
        le=1.0,
        description="""<what>Decision confidence</what>

<when>ALWAYS required</when>

<how>Float between 0 and 1</how>"""
    )
    
    def get_top_questions(self, n: int = 3) -> List[ExplorationQuestion]:
        """Get top N questions by priority (higher score = higher priority)."""
        sorted_questions = sorted(self.exploration_questions, key=lambda q: q.priority, reverse=True)
        return sorted_questions[:n]
    
    def get_questions_by_type(self, exploration_type: str) -> List[ExplorationQuestion]:
        """Filter questions by exploration type."""
        return [q for q in self.exploration_questions if q.exploration_type == exploration_type]


__all__ = [
    "ExplorationQuestion",
    "ReplanDecision",
]
