# -*- coding: utf-8 -*-
"""
Replanner Agent Prompts

按照 PROMPT_AND_MODEL_GUIDE.md 规范实现的 Prompt 模板。

设计原则（遵循规范文档）：
- Prompt 告诉 LLM 如何思考（Role, Task, Domain Knowledge, Constraints）
- Schema（数据模型）告诉 LLM 输出什么（字段定义、XML 标签）
- 使用 VizQLPrompt 基类的 4 段式结构
- Output Model 自动注入 JSON Schema

核心功能：
- 评估当前洞察的完成度
- 识别缺失的分析方面
- 基于 dimension_hierarchy 生成多个探索问题
- 为每个问题分配优先级

Design Specification: insight-design.md
"""

from typing import Type
from pydantic import BaseModel

from tableau_assistant.src.agents.base.prompt import VizQLPrompt
from tableau_assistant.src.core.models import ReplanDecision


class ReplannerPrompt(VizQLPrompt):
    """
    Replanner Agent Prompt - 智能重规划
    
    设计原则：
    - Prompt 告诉 LLM 如何思考（领域知识 + 推理步骤）
    - Schema 告诉 LLM 输出什么（字段填写规则）
    - Prompt 不包含具体字段名和关键词映射
    - 思考步骤与 Schema 中的 <decision_rule> 对应
    """
    
    def get_role(self) -> str:
        """
        定义 LLM 的角色（激活知识子空间）
        
        Target: ~20 words
        """
        return """Data analysis strategist who evaluates insight completeness and orchestrates exploration.

Expertise: completeness assessment, gap identification, exploration planning, question generation, priority assignment"""
    
    def get_task(self) -> str:
        """
        定义任务（聚焦注意力）
        
        Target: ~50 words with implicit CoT
        """
        return """Evaluate current insights and decide if more analysis is needed.

Process: Assess completeness -> Identify gaps -> Select exploration type -> Generate questions -> Assign priority -> Output JSON"""
    
    def get_specific_domain_knowledge(self) -> str:
        """
        提供领域知识和思考步骤（HOW to think）
        
        注意：不包含具体字段名和关键词映射，这些在 Schema 的 <decision_rule> 中
        
        Target: ~200 words
        """
        return """**Think step by step:**

Step 1: Assess completeness
- Does the insight directly answer the user's question?
- Are all aspects of the question addressed?
- Is there enough detail to understand "why"?
- Score: 0.9-1.0 (complete), 0.7-0.9 (mostly), 0.5-0.7 (partial), <0.5 (insufficient)

Step 2: Identify gaps (if completeness < 0.9)
- What aspects are missing from the analysis?
- Which dimensions have not been explored?
- Are there unexplored relationships or patterns?

Step 3: Check deduplication (CRITICAL)
- Review answered_questions list for similar questions
- "Similar" = same dimension + same analysis type
- If dimension in current_dimensions, only drill_down or cross_dimension allowed
- Never repeat exact question text

Step 4: Select exploration type based on context
- Need finer granularity -> drill_down
- Need coarser granularity -> roll_up
- Need temporal analysis -> time_series
- Need horizontal comparison -> peer_comparison
- Need multi-dimension analysis -> cross_dimension
- Found anomaly -> anomaly_investigation
- Need relationship analysis -> correlation_analysis

Step 5: Generate questions
- Questions generated by YOU directly, NOT from templates
- Use actual entity names from insights (e.g., "A店" not "该门店")
- Each question targets ONE specific dimension
- Questions in Chinese (用户语言)

Step 6: Assign priority
- Priority 1: Directly answers user's question
- Priority 2-3: Provides key supporting information
- Priority 4-6: Deepens understanding
- Priority 7-10: Edge exploration

**Using dimension_hierarchy:**
- geographic category -> drill_down to city/district
- time category -> time_series analysis
- product category -> drill_down to subcategory
- level 1-2 (coarse) -> can drill_down
- level 4-5 (fine) -> can roll_up

**Using data_insight_profile:**
- distribution_type == "long_tail" -> Focus on top performers
- anomaly_ratio > 0.05 -> anomaly_investigation
- clusters exist -> Compare cluster characteristics"""
    
    def get_constraints(self) -> str:
        """
        定义约束条件
        
        Target: 3-5 rules, ~10 words each
        """
        return """MUST:
- Generate questions in Chinese with actual entity names
- Check answered_questions before generating new questions
- Follow <decision_rule> in Schema for each field

MUST NOT:
- Use template placeholders like {entity}
- Generate more than 5 questions per round
- Repeat questions already in answered_questions
- Generate same-dimension questions unless drill_down/cross_dimension"""
    
    def get_user_template(self) -> str:
        return """## 原始问题
{original_question}

## 当前洞察
{insights_summary}

## 数据洞察画像（Phase 1 统计分析结果）
{data_insight_profile}

## 维度层级信息
{dimension_hierarchy}

## 当前已分析的维度
{current_dimensions}

## 已回答的问题（去重参考）
{answered_questions}

## 重规划轮次
当前轮次: {current_round}
最大轮次: {max_rounds}

Analyze the current insights and output ReplanDecision."""
    
    def get_output_model(self) -> Type[BaseModel]:
        return ReplanDecision


# Prompt 实例
REPLANNER_PROMPT = ReplannerPrompt()


__all__ = [
    "ReplannerPrompt",
    "REPLANNER_PROMPT",
]
