"""
Replanner Agent Prompts

按照 PROMPT_AND_MODEL_GUIDE.md 规范实现的 Prompt 模板。

核心原则：
- Prompt 教 LLM 如何评估分析完整性
- Schema 告诉 LLM 输出什么（ReplanDecision 结构）
- 问题由 LLM 直接生成，不使用模板！
- 支持多问题并行执行（类 Tableau Pulse）

Design Specification: insight-design.md
"""

from typing import Type
from pydantic import BaseModel

from tableau_assistant.src.agents.base.prompt import VizQLPrompt
from tableau_assistant.src.models.replanner import ReplanDecision


class ReplannerPrompt(VizQLPrompt):
    """
    Replanner Agent Prompt - 智能重规划
    
    核心理念（来自设计文档）：
    1. 评估当前洞察的完成度
    2. 识别缺失的分析方面
    3. 基于 dimension_hierarchy 生成多个探索问题
    4. 为每个问题分配优先级
    
    关键：问题由 LLM 直接生成，不使用模板！
    """
    
    def get_role(self) -> str:
        return "Data analysis strategist who evaluates insight completeness and generates exploration questions."
    
    def get_task(self) -> str:
        return """Evaluate current insights and decide if more analysis is needed.

Process: Evaluate completeness → Identify gaps → Generate questions → Prioritize

If completeness_score >= 0.9: should_replan = false
If completeness_score < 0.9 AND gaps exist: should_replan = true, generate exploration_questions"""
    
    def get_specific_domain_knowledge(self) -> str:
        return """**Completeness Evaluation Criteria:**

1. Question Coverage:
   - Does the insight directly answer the user's question?
   - Are all aspects of the question addressed?

2. Depth of Analysis:
   - Is there enough detail to understand "why"?
   - Are there supporting evidence and comparisons?

3. Dimension Coverage:
   - Have relevant dimensions been explored?
   - Are there unexplored dimensions that could provide insights?

**Exploration Types (exploration_type):**

| Type | When to Use | Example |
|------|-------------|---------|
| drill_down | Need finer granularity | "各产品类别的销售额？" |
| roll_up | Need coarser granularity | "按地区汇总的销售额？" |
| time_series | Need temporal analysis | "过去12个月的趋势？" |
| peer_comparison | Need horizontal comparison | "与同类门店对比？" |
| cross_dimension | Need multi-dimension analysis | "产品×地区的交叉分析？" |
| anomaly_investigation | Found anomaly, need investigation | "异常值的原因？" |
| correlation_analysis | Need relationship analysis | "销售额与利润的关系？" |

**Priority Assignment Rules:**

- Priority 1: Directly answers user's question
- Priority 2-3: Provides key supporting information
- Priority 4-6: Deepens understanding
- Priority 7-10: Edge exploration

**Question Generation Rules (CRITICAL):**

1. Questions are generated by YOU directly, NOT from templates!
2. Questions should be specific and actionable
3. Questions should reference actual data (e.g., "A店" not "该门店")
4. Questions should be in Chinese (用户语言)
5. Each question should target ONE specific dimension

**Using dimension_hierarchy:**

- Use category to determine exploration direction:
  - geographic → drill_down to city/district
  - time → time_series analysis
  - product → drill_down to subcategory
  - customer → peer_comparison
  
- Use level to determine granularity:
  - level 1-2 (coarse) → can drill_down
  - level 4-5 (fine) → can roll_up

**Using data_insight_profile:**

- distribution_type == "long_tail" → Focus on top performers
- anomaly_ratio > 0.05 → anomaly_investigation
- clusters exist → Compare cluster characteristics
- trend detected → time_series for deeper analysis"""
    
    def get_constraints(self) -> str:
        return """MUST: Generate questions in Chinese, use actual entity names from insights
MUST: Assign priority based on relevance to user's question
MUST NOT: Use template placeholders like {entity}, generate specific questions
MUST NOT: Generate more than 5 questions per round
MUST NOT: Repeat questions that have already been answered"""
    
    def get_user_template(self) -> str:
        return """## 原始问题
{original_question}

## 当前洞察
{insights_summary}

## 数据洞察画像（Phase 1 统计分析结果）
{data_insight_profile}

## 维度层级信息
{dimension_hierarchy}

## 当前已分析的维度
{current_dimensions}

## 重规划轮次
当前轮次: {current_round}
最大轮次: {max_rounds}

## 任务
1. 评估当前洞察对原始问题的回答完整度 (0-1)
2. 如果 completeness_score < 0.9，识别缺失的分析方面
3. 基于 dimension_hierarchy 和 data_insight_profile 生成探索问题
4. 为每个问题分配优先级和探索类型

注意：
- 问题由你直接生成，不要使用模板！
- 问题要具体，使用洞察中的实际实体名称
- 问题用中文表达"""
    
    def get_output_model(self) -> Type[BaseModel]:
        return ReplanDecision


# Prompt 实例
REPLANNER_PROMPT = ReplannerPrompt()


__all__ = [
    "ReplannerPrompt",
    "REPLANNER_PROMPT",
]
