import json
import re
import requests
import asyncio
from typing import Any, Dict, List, Optional
from tableau_assistant.src.utils.tableau.utils import http_post

# 使用新的证书管理包
try:
    from tableau_assistant.cert_manager import get_ssl_config
    def get_aiohttp_ssl():
        return get_ssl_config().get_aiohttp_ssl_param()
except ImportError:
    # 兼容旧版本
    from tableau_assistant.src.utils.ssl_config import get_aiohttp_ssl


def _simplify_fields(raw_fields: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    精简字段元数据，仅保留必要信息。
    
    规则：
    1. 去除隐藏字段（isHidden=True）
    2. 验证计算字段引用的字段是否存在，删除无效的计算字段
    3. 仅保留必要键：name, role, dataType, dataCategory, aggregation
    4. 如果有计算字段的formula为对单一原始字段的直接引用（如"[shop_id]"），
       则删除该原始字段，仅保留计算字段
    
    Args:
        raw_fields: 原始字段列表
        
    Returns:
        精简后的字段列表
    """
    # 1. 过滤隐藏字段
    visible_fields = [f for f in raw_fields if not f.get('isHidden')]
    
    # 2. 构建所有字段名称集合（用于验证引用）
    all_field_names = {f.get('name', '') for f in visible_fields if f.get('name')}
    
    # 3. 验证计算字段并找出单一字段引用
    calculated_field_refs = {}  # {原始字段名: 计算字段}
    valid_calculated_fields = set()  # 有效的计算字段名称
    
    for field in visible_fields:
        if field.get('__typename') == 'CalculatedField':
            formula = field.get('formula', '')
            field_name = field.get('name', '')
            
            # 提取公式中所有的字段引用 [field_name]
            referenced_fields = re.findall(r'\[([^\]]+)\]', formula)
            
            # 检查所有引用的字段是否存在
            all_refs_exist = all(ref in all_field_names for ref in referenced_fields)
            
            if all_refs_exist:
                # 计算字段有效
                valid_calculated_fields.add(field_name)
                
                # 检查是否为单一字段引用
                if re.match(r'^\[([^\]]+)\]$', formula.strip()):
                    ref_field_name = referenced_fields[0]
                    calculated_field_refs[ref_field_name] = field
            # 如果引用的字段不存在，该计算字段将被过滤掉（不加入valid_calculated_fields）
    
    # 4. 过滤字段：去除被引用的原始字段和无效的计算字段
    filtered_fields = []
    for field in visible_fields:
        field_name = field.get('name', '')
        field_type = field.get('__typename', '')
        
        # 如果是计算字段，检查是否有效
        if field_type == 'CalculatedField':
            if field_name in valid_calculated_fields:
                filtered_fields.append(field)
            # 无效的计算字段被跳过
            continue
        
        # 如果是被计算字段引用的原始字段，跳过它
        if field_name in calculated_field_refs:
            continue
        
        # 其他字段保留
        filtered_fields.append(field)
    
    # 5. 精简字段，仅保留必要键
    simplified_fields = []
    essential_keys = {'name', 'role', 'dataType', 'dataCategory', 'aggregation'}
    
    for field in filtered_fields:
        simplified = {}
        for key in essential_keys:
            if key in field:
                simplified[key] = field[key]
        
        # 如果是计算字段，保留formula以便理解
        if field.get('__typename') == 'CalculatedField' and 'formula' in field:
            simplified['formula'] = field['formula']
        
        # 确保至少有name字段
        if 'name' in simplified:
            simplified_fields.append(simplified)
    
    return simplified_fields


def get_datasource_query(luid):
    query = f"""
    query datasourceFieldInfo {{
        publishedDatasources(filter: {{ luid: "{luid}" }}) {{
          name
          description
          owner {{
            name
          }}
          fields {{
            name
            isHidden
            description
            descriptionInherited {{
              attribute
              value
            }}
            fullyQualifiedName
            __typename
            ... on AnalyticsField {{
              __typename
            }}
            ... on ColumnField {{
              dataCategory
              role
              dataType
              defaultFormat
              semanticRole
              aggregation
              aggregationParam
            }}
            ... on CalculatedField {{
              dataCategory
              role
              dataType
              defaultFormat
              semanticRole
              aggregation
              aggregationParam
              formula
              isAutoGenerated
              hasUserReference
            }}
            ... on BinField {{
              dataCategory
              role
              dataType
              formula
              binSize
            }}
            ... on GroupField {{
              dataCategory
              role
              dataType
              hasOther
            }}
            ... on CombinedSetField {{
              delimiter
              combinationType
            }}
          }}
        }}
      }}
    """

    return query


async def get_data_dictionary_async(api_key: str, domain: str, datasource_luid: str, site: Optional[str] = None, include_samples: bool = True) -> Dict[str, Any]:
    # 规范化域名：去掉尾随斜杠
    domain = (domain or "").rstrip("/")
    full_url = f"{domain}/api/metadata/graphql"

    query = get_datasource_query(datasource_luid)

    payload = {
        "query": query,
        "variables": {}
    }

    headers = {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
        'X-Tableau-Auth': api_key
    }
    if site:
        headers['X-Tableau-Site'] = site

    response = await http_post(endpoint=full_url, headers=headers, payload=payload)

    # Check if the request was successful (status code 200)
    if response['status'] == 200:
        # Parse the response data
        response_data = response['data']
        if 'errors' in response_data:
            error_message = f"GraphQL errors: {response_data['errors']}"
            raise RuntimeError(error_message)

        json_data = response_data['data']['publishedDatasources'][0]

        # Simplify fields - remove hidden, keep only essential keys
        raw_fields = json_data.get('fields', [])
        simplified_fields = _simplify_fields(raw_fields)
        
        # 批量获取维度样例数据（如果启用）
        if include_samples:
            # 提取所有维度字段名和第一个度量字段
            dimension_names = [f['name'] for f in simplified_fields if f.get('role', '').upper() == 'DIMENSION']
            measure_field = None
            for f in simplified_fields:
                if f.get('role', '').upper() == 'MEASURE':
                    measure_field = f['name']
                    break
            
            if dimension_names and measure_field:
                # 分批异步获取样例数据
                batch_size = 1  # 每批1个维度
                
                batches = [dimension_names[i:i + batch_size] for i in range(0, len(dimension_names), batch_size)]
                
                async def fetch_batch_async(batch):
                    """异步获取一批样例数据"""
                    try:
                        print(f"  正在获取批次: {batch[:2]}... ({len(batch)}个维度)")
                        result = await _fetch_dimension_samples_async(
                            api_key=api_key,
                            domain=domain,
                            datasource_luid=datasource_luid,
                            dimension_names=batch,
                            measure_field=measure_field,
                            sample_size=1,
                            site=site
                        )
                        print(f"  批次完成: 获得 {len(result)} 个维度的样例")
                        return result
                    except Exception as e:
                        print(f"Warning: Failed to fetch samples for batch {batch[:2]}: {e}")
                        import traceback
                        traceback.print_exc()
                        return {}
                
                # 并发执行所有批次
                results = await asyncio.gather(*[fetch_batch_async(batch) for batch in batches])
                
                # 合并结果
                samples_dict = {}
                for result in results:
                    samples_dict.update(result)
                
                print(f"异步获取完成，获得 {len(samples_dict)} 个维度的样例数据")
                
                # 将样例数据和unique_count写入fields
                written_count = 0
                for field in simplified_fields:
                    if field.get('role', '').upper() == 'DIMENSION':
                        field_name = field['name']
                        if field_name in samples_dict:
                            dim_data = samples_dict[field_name]
                            if isinstance(dim_data, dict):
                                # 新格式: {"sample_values": [...], "unique_count": N}
                                if dim_data.get('sample_values'):
                                    field['sample_values'] = dim_data['sample_values']
                                    written_count += 1
                                    print(f"  写入样例: {field_name} = {dim_data['sample_values']}")
                                if 'unique_count' in dim_data:
                                    field['unique_count'] = dim_data['unique_count']
                                    print(f"  写入COUNTD: {field_name} = {dim_data['unique_count']}")
                            else:
                                # 兼容旧格式: 直接是列表
                                if dim_data:
                                    field['sample_values'] = dim_data
                                    written_count += 1
                                    print(f"  写入样例(旧格式): {field_name} = {dim_data}")
                        else:
                            print(f"  未找到样例: {field_name}")
                print(f"共写入 {written_count} 个维度的样例数据")

        return {
            'datasource_name': json_data.get('name'),
            'datasource_description': json_data.get('description'),
            'datasource_owner': json_data.get('owner', {}).get('name'),
            'datasource_luid': datasource_luid,

            # Simplified fields with only essential information
            'fields': simplified_fields,

            # Minimal helpful additions
            'field_count': len(simplified_fields),
            'field_names': [f['name'] for f in simplified_fields],

            # Full raw response for debugging if needed
            'raw_graphql_response': json_data
        }
    else:
        error_message = (
            f"Failed to query Tableau's Metadata API. "
            f"Status code: {response['status']}. Response: {response['data']}"
        )
        raise RuntimeError(error_message)


async def _fetch_dimension_samples_async(
    api_key: str,
    domain: str,
    datasource_luid: str,
    dimension_names: List[str],
    measure_field: str,
    sample_size: int = 1,
    site: Optional[str] = None
) -> Dict[str, Dict[str, Any]]:
    """
    异步批量获取一批维度的样例数据和唯一值数量
    
    使用VizQL Data Service API + TopN Filter查询一批维度（3-5个），限制只返回N条数据
    同时使用COUNTD聚合获取唯一值数量
    配合asyncio.gather实现真正的异步并发
    
    Args:
        api_key: Tableau认证token
        domain: Tableau域名
        datasource_luid: 数据源LUID
        dimension_names: 维度字段名称列表（建议3-5个）
        measure_field: 用于TopN排序的度量字段
        sample_size: 每个维度的样例数量（默认1条）
        site: Tableau站点
    
    Returns:
        字典，key是维度名称，value是包含sample_values和unique_count的字典
        例如: {"维度1": {"sample_values": ["值1"], "unique_count": 100}}
    """
    if not dimension_names:
        return {}
    
    try:
        import aiohttp
        
        # 策略：为每个维度字段单独查询
        # 1. 对每个维度：使用MAX聚合函数获取最大值，并筛选度量不为空
        # 2. 一次性查询所有维度的COUNTD
        
        # 为每个维度创建单独的样例查询
        # 第一阶段：获取所有维度的MAX值（不加筛选器）
        # 用于维度层级LLM推断
        sample_queries = []
        for dim in dimension_names:
            query = {
                "fields": [
                    {
                        "fieldCaption": dim,
                        "function": "MAX"  # 使用MAX聚合获取维度最大值
                    }
                ]
                # 不添加筛选器，获取纯粹的最大值
            }
            sample_queries.append((dim, query))
        
        # 查询COUNTD（唯一值数量）
        query_countd = {
            "fields": [
                {
                    "fieldCaption": dim,
                    "function": "COUNTD"  # 使用COUNTD聚合函数
                } for dim in dimension_names
            ]
        }
        
        print(f"    异步查询维度样例和COUNTD: {dimension_names}")
        print(f"    为每个维度单独查询样例值（共{len(sample_queries)}个查询）")
        print(f"    COUNTD查询: {query_countd}")
        
        # 构建请求
        full_url = f"{domain}/api/v1/vizql-data-service/query-datasource"
        headers = {
            'X-Tableau-Auth': api_key,
            'Content-Type': 'application/json'
        }
        if site:
            headers['X-Tableau-Site'] = site
        
        # 异步HTTP请求 - 并发执行所有查询
        # 使用统一的SSL配置
        ssl_param = get_aiohttp_ssl()
        async with aiohttp.ClientSession() as session:
            # 为每个维度创建查询任务
            async def fetch_dimension_samples(dim_name, query):
                payload = {
                    "datasource": {"datasourceLuid": datasource_luid},
                    "query": query
                }
                async with session.post(full_url, json=payload, headers=headers, ssl=ssl_param) as response:
                    if response.status == 200:
                        result = await response.json()
                        return (dim_name, result)
                    else:
                        error_text = await response.text()
                        print(f"    警告: 维度 {dim_name} 样例查询失败: {response.status}")
                        return (dim_name, {"data": []})
            
            # COUNTD查询
            async def fetch_countd():
                payload = {
                    "datasource": {"datasourceLuid": datasource_luid},
                    "query": query_countd
                }
                async with session.post(full_url, json=payload, headers=headers, ssl=ssl_param) as response:
                    if response.status == 200:
                        return await response.json()
                    else:
                        error_text = await response.text()
                        raise RuntimeError(f"VDS countd query failed: {response.status}, {error_text}")
            
            # 并发执行所有查询
            sample_tasks = [fetch_dimension_samples(dim, query) for dim, query in sample_queries]
            all_results = await asyncio.gather(*sample_tasks, fetch_countd())
            
            # 分离样例结果和COUNTD结果
            sample_results = all_results[:-1]  # 前N个是样例查询结果
            result_countd = all_results[-1]    # 最后一个是COUNTD结果
        
        print(f"    样例查询完成: {len(sample_results)}个维度")
        print(f"    COUNTD查询结果: {type(result_countd)}")
        
        # 初始化结果
        dimension_results = {dim: {"sample_values": [], "unique_count": 0} for dim in dimension_names}
        
        # 处理每个维度的样例值（每个维度返回MAX聚合值）
        print(f"    开始处理样例数据（MAX聚合值）")
        for dim_name, result in sample_results:
            data = result.get("data", [])
            print(f"    维度 {dim_name} 返回 {len(data)} 条数据")
            
            if data and len(data) > 0:
                row = data[0]  # MAX聚合只返回一行
                
                # 提取MAX值
                max_value = None
                if isinstance(row, dict):
                    # 尝试不同的键名
                    max_value = row.get(f"MAX({dim_name})") or row.get(dim_name)
                elif isinstance(row, list) and len(row) > 0:
                    max_value = row[0]
                
                if max_value is not None:
                    value_str = str(max_value).strip()
                    if value_str:
                        dimension_results[dim_name]["sample_values"].append(value_str)
                        print(f"    维度 {dim_name} MAX值: {value_str}")
        
        # 提取COUNTD值
        data_countd = result_countd.get("data", [])
        print(f"    COUNTD数据行数: {len(data_countd)}")
        
        # 处理COUNTD值
        if data_countd:
            print(f"    开始处理COUNTD数据")
            countd_row = data_countd[0] if data_countd else {}
            print(f"    COUNTD数据: {countd_row}")
            
            if isinstance(countd_row, dict):
                for dim in dimension_names:
                    # COUNTD字段可能以 "COUNTD(维度名)" 的格式返回
                    countd_value = countd_row.get(dim) or countd_row.get(f"COUNTD({dim})")
                    if countd_value is not None:
                        try:
                            dimension_results[dim]["unique_count"] = int(countd_value)
                            print(f"    维度 {dim} COUNTD: {countd_value}")
                        except (ValueError, TypeError):
                            print(f"    警告: 无法解析 {dim} 的COUNTD值: {countd_value}")
            elif isinstance(countd_row, list):
                for i, dim in enumerate(dimension_names):
                    if i < len(countd_row) and countd_row[i] is not None:
                        try:
                            dimension_results[dim]["unique_count"] = int(countd_row[i])
                            print(f"    维度 {dim} COUNTD: {countd_row[i]}")
                        except (ValueError, TypeError):
                            print(f"    警告: 无法解析 {dim} 的COUNTD值: {countd_row[i]}")
        
        print(f"    提取结果: {[(k, len(v['sample_values']), v['unique_count']) for k, v in dimension_results.items()]}")
        return dimension_results
        
    except Exception as e:
        print(f"Warning: Failed to fetch dimension samples: {e}")
        import traceback
        traceback.print_exc()
        return {dim: {"sample_values": [], "unique_count": 0} for dim in dimension_names}


async def fetch_valid_max_date_async(
    api_key: str,
    domain: str,
    datasource_luid: str,
    date_field_name: str,
    measure_field_name: str,
    site: Optional[str] = None
) -> Optional[str]:
    """
    获取日期字段的有效最大值（度量不为空且不为0的最大日期）
    
    这个函数在维度层级LLM识别出日期字段和度量字段后调用
    用于获取有业务数据的最大日期
    
    Args:
        api_key: Tableau认证token
        domain: Tableau域名
        datasource_luid: 数据源LUID
        date_field_name: 日期字段名称
        measure_field_name: 度量字段名称（用于筛选）
        site: Tableau站点
    
    Returns:
        有效的最大日期字符串，如果查询失败返回None
    """
    try:
        import aiohttp
        
        # 构建查询：获取日期字段的MAX值，筛选度量不为空且不为0
        query = {
            "fields": [
                {
                    "fieldCaption": date_field_name,
                    "function": "MAX"
                }
            ],
            "filters": [
                {
                    "filterType": "QUANTITATIVE_NUMERICAL",
                    "field": {"fieldCaption": measure_field_name},
                    "quantitativeFilterType": "RANGE",
                    "min": 0.000001,  # 大于0（排除0值）
                    "max": 999999999999,  # 正无穷大
                    "includeNulls": False  # 排除空值
                }
            ]
        }
        
        print(f"    查询日期字段 {date_field_name} 的有效最大值（筛选 {measure_field_name} > 0）")
        
        # 构建请求
        full_url = f"{domain}/api/v1/vizql-data-service/query-datasource"
        headers = {
            'X-Tableau-Auth': api_key,
            'Content-Type': 'application/json'
        }
        if site:
            headers['X-Tableau-Site'] = site
        
        payload = {
            "datasource": {"datasourceLuid": datasource_luid},
            "query": query
        }
        
        # 发送请求
        # 使用统一的SSL配置
        ssl_param = get_aiohttp_ssl()
        async with aiohttp.ClientSession() as session:
            async with session.post(full_url, json=payload, headers=headers, ssl=ssl_param) as response:
                if response.status == 200:
                    result = await response.json()
                    data = result.get("data", [])
                    
                    if data and len(data) > 0:
                        row = data[0]
                        
                        # 提取MAX值
                        max_date = None
                        if isinstance(row, dict):
                            max_date = row.get(f"MAX({date_field_name})") or row.get(date_field_name)
                        elif isinstance(row, list) and len(row) > 0:
                            max_date = row[0]
                        
                        if max_date is not None:
                            max_date_str = str(max_date).strip()
                            
                            # 与今天-1比较，取最小值
                            from datetime import datetime, timedelta
                            try:
                                # 尝试解析日期 - 支持多种格式
                                datasource_max_date = None
                                try:
                                    # 尝试 ISO 格式
                                    datasource_max_date = datetime.fromisoformat(max_date_str).date()
                                except ValueError:
                                    # 尝试其他常见格式
                                    for fmt in ["%Y/%m/%d", "%Y-%m-%d", "%Y/%m/%d %H:%M:%S", "%Y-%m-%d %H:%M:%S"]:
                                        try:
                                            datasource_max_date = datetime.strptime(max_date_str, fmt).date()
                                            break
                                        except ValueError:
                                            continue
                                
                                if datasource_max_date is None:
                                    print(f"    ⚠️  无法解析日期格式: {max_date_str}")
                                    return None
                                
                                today_minus_1 = datetime.now().date() - timedelta(days=1)
                                
                                # 取两者最小值
                                valid_max_date = min(datasource_max_date, today_minus_1)
                                valid_max_date_str = valid_max_date.isoformat()
                                
                                print(f"    ✓ 数据源最大日期: {datasource_max_date}")
                                print(f"    ✓ 今天-1: {today_minus_1}")
                                print(f"    ✓ 有效最大日期（取最小值）: {valid_max_date_str}")
                                
                                return valid_max_date_str
                            except Exception as e:
                                print(f"    ⚠️  日期处理失败: {e}")
                                return None
                        else:
                            print(f"    ⚠️  未找到有效最大日期")
                            return None
                    else:
                        print(f"    ⚠️  查询返回空结果")
                        return None
                else:
                    error_text = await response.text()
                    print(f"    ✗ 查询失败: {response.status}, {error_text}")
                    return None
    
    except Exception as e:
        print(f"    ✗ 查询有效最大日期失败: {e}")
        import traceback
        traceback.print_exc()
        return None


def _fetch_dimension_samples(
    api_key: str,
    domain: str,
    datasource_luid: str,
    dimension_names: List[str],
    measure_field: str,
    sample_size: int = 1,
    site: Optional[str] = None
) -> Dict[str, List[str]]:
    """
    批量获取一批维度的样例数据（API层面限制返回行数）
    
    使用VizQL Data Service API + TopN Filter查询一批维度（3-5个），限制只返回N条数据
    配合外层的并发调用，可以快速获取所有维度的样例数据
    
    Args:
        api_key: Tableau认证token
        domain: Tableau域名
        datasource_luid: 数据源LUID
        dimension_names: 维度字段名称列表（建议3-5个）
        measure_field: 用于TopN排序的度量字段
        sample_size: 每个维度的样例数量（默认1条）
        site: Tableau站点
    
    Returns:
        字典，key是维度名称，value是样例值列表
    """
    if not dimension_names:
        return {}
    
    try:
        from tableau_assistant.src.utils.tableau.vizql_data_service import query_vds
        
        # 使用TopN Filter限制返回行数
        # 使用度量字段排序,howMany=1只返回1条数据
        sort_field = dimension_names[0]
        
        query = {
            "fields": [{"fieldCaption": dim} for dim in dimension_names],
            "filters": [
                {
                    "filterType": "TOP",
                    "field": {"fieldCaption": sort_field},
                    "fieldToMeasure": {"fieldCaption": measure_field, "function": "SUM"},
                    "howMany": 1,  # 只返回1条数据
                    "direction": "TOP"
                }
            ]
        }
        
        # 查询数据
        result = query_vds(
            api_key=api_key,
            datasource_luid=datasource_luid,
            url=domain,
            query=query
        )
        
        # 提取每个维度的样例值
        data = result.get("data", [])
        if not data:
            return {dim: [] for dim in dimension_names}
        
        # 为每个维度收集样例值
        dimension_samples = {dim: [] for dim in dimension_names}
        
        for row in data:
            if isinstance(row, dict):
                # 字典格式：{dim1: value1, dim2: value2, ...}
                for dim in dimension_names:
                    value = row.get(dim)
                    if value is not None:
                        dimension_samples[dim].append(str(value))
            elif isinstance(row, list):
                # 列表格式：[value1, value2, ...]
                for i, dim in enumerate(dimension_names):
                    if i < len(row) and row[i] is not None:
                        dimension_samples[dim].append(str(row[i]))
        
        return dimension_samples
        
    except Exception as e:
        # 获取样例数据失败不影响主流程，返回空样例
        print(f"Warning: Failed to fetch dimension samples: {e}")
        return {dim: [] for dim in dimension_names}


def get_data_dictionary(api_key: str, domain: str, datasource_luid: str, site: Optional[str] = None, include_samples: bool = True) -> Dict[str, Any]:
    """
    获取数据源元数据
    
    Args:
        api_key: Tableau认证token
        domain: Tableau域名
        datasource_luid: 数据源LUID
        site: Tableau站点
        include_samples: 是否包含维度样例数据（默认True，每个维度3条样例）
    
    Returns:
        元数据字典
    """
    # 规范化域名：去掉尾随斜杠
    domain = (domain or "").rstrip("/")
    full_url = f"{domain}/api/metadata/graphql"

    query = get_datasource_query(datasource_luid)

    payload = json.dumps({
        "query": query,
        "variables": {}
    })

    headers = {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
        'X-Tableau-Auth': api_key
    }
    if site:
        headers['X-Tableau-Site'] = site

    response = requests.post(full_url, headers=headers, data=payload)
    response.raise_for_status()  # Raise an exception for bad status codes

    response_data = response.json()
    if 'errors' in response_data:
        error_message = f"GraphQL errors: {response_data['errors']}"
        raise RuntimeError(error_message)

    # Expect at least one match for the given luid
    ds_list = response_data['data'].get('publishedDatasources') or []
    if not ds_list:
        raise RuntimeError("No datasource found for provided LUID")

    json_data = ds_list[0]

    # Simplify fields - remove hidden, keep only essential keys
    raw_fields = json_data.get('fields', [])
    simplified_fields = _simplify_fields(raw_fields)
    
    # 批量获取维度样例数据（如果启用）
    if include_samples:
        # 提取所有维度字段名和第一个度量字段
        dimension_names = [f['name'] for f in simplified_fields if f.get('role', '').upper() == 'DIMENSION']
        measure_field = None
        for f in simplified_fields:
            if f.get('role', '').upper() == 'MEASURE':
                measure_field = f['name']
                break
        
        if dimension_names and measure_field:
            # 分批异步获取样例数据
            import asyncio
            
            batch_size = 1  # 每批1个维度
            
            async def fetch_all_batches():
                """异步获取所有批次的样例数据"""
                batches = [dimension_names[i:i + batch_size] for i in range(0, len(dimension_names), batch_size)]
                
                async def fetch_batch_async(batch):
                    """异步获取一批样例数据"""
                    try:
                        print(f"  正在获取批次: {batch[:2]}... ({len(batch)}个维度)")
                        result = await _fetch_dimension_samples_async(
                            api_key=api_key,
                            domain=domain,
                            datasource_luid=datasource_luid,
                            dimension_names=batch,
                            measure_field=measure_field,
                            sample_size=1,
                            site=site
                        )
                        print(f"  批次完成: 获得 {len(result)} 个维度的样例")
                        return result
                    except Exception as e:
                        print(f"Warning: Failed to fetch samples for batch {batch[:2]}: {e}")
                        import traceback
                        traceback.print_exc()
                        return {}
                
                # 并发执行所有批次
                results = await asyncio.gather(*[fetch_batch_async(batch) for batch in batches])
                
                # 合并结果
                samples_dict = {}
                for result in results:
                    samples_dict.update(result)
                return samples_dict
            
            # 运行异步任务
            try:
                loop = asyncio.get_event_loop()
            except RuntimeError:
                loop = asyncio.new_event_loop()
                asyncio.set_event_loop(loop)
            
            print(f"开始异步获取 {len(dimension_names)} 个维度的样例数据...")
            samples_dict = loop.run_until_complete(fetch_all_batches())
            print(f"异步获取完成，获得 {len(samples_dict)} 个维度的样例数据")
            print(f"samples_dict内容: {list(samples_dict.keys())[:5]}...")
            
            # 将样例数据和unique_count写入fields
            written_count = 0
            for field in simplified_fields:
                if field.get('role', '').upper() == 'DIMENSION':
                    field_name = field['name']
                    if field_name in samples_dict:
                        dim_data = samples_dict[field_name]
                        if isinstance(dim_data, dict):
                            # 新格式: {"sample_values": [...], "unique_count": N}
                            if dim_data.get('sample_values'):
                                field['sample_values'] = dim_data['sample_values']
                                written_count += 1
                                print(f"  写入样例: {field_name} = {dim_data['sample_values']}")
                            if 'unique_count' in dim_data:
                                field['unique_count'] = dim_data['unique_count']
                                print(f"  写入COUNTD: {field_name} = {dim_data['unique_count']}")
                        else:
                            # 兼容旧格式: 直接是列表
                            if dim_data:
                                field['sample_values'] = dim_data
                                written_count += 1
                                print(f"  写入样例(旧格式): {field_name} = {dim_data}")
                    else:
                        print(f"  未找到样例: {field_name}")
            print(f"共写入 {written_count} 个维度的样例数据")

    return {
        'datasource_name': json_data.get('name'),
        'datasource_description': json_data.get('description'),
        'datasource_owner': json_data.get('owner', {}).get('name'),
        'datasource_luid': datasource_luid,

        # Simplified fields with only essential information
        'fields': simplified_fields,

        # Minimal helpful additions
        'field_count': len(simplified_fields),
        'field_names': [f['name'] for f in simplified_fields],

        # Full raw response for debugging if needed
        'raw_graphql_response': json_data
    }


# =========================
# New: Lookup by datasource name, then fetch metadata fields
# =========================

def _graphql_post(domain: str, api_key: str, query: str, variables: Optional[Dict[str, Any]] = None, site: Optional[str] = None) -> Dict[str, Any]:
    """Lightweight helper to call Tableau Metadata GraphQL endpoint."""
    # 规范化域名：去掉尾随斜杠
    domain = (domain or "").rstrip("/")
    full_url = f"{domain}/api/metadata/graphql"
    headers = {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
        'X-Tableau-Auth': api_key
    }
    if site:
        headers['X-Tableau-Site'] = site
    payload = json.dumps({
        "query": query,
        "variables": variables or {}
    })
    resp = requests.post(full_url, headers=headers, data=payload)
    resp.raise_for_status()
    data = resp.json()
    if 'errors' in data:
        raise RuntimeError(f"GraphQL errors: {data['errors']}")
    return data


def get_datasource_luid_by_name(api_key: str, domain: str, datasource_name: str, site: Optional[str] = None) -> Optional[str]:
    """
    通过名称查找已发布数据源的 LUID（按策略多次尝试）：
      1) exact + project：name == dsName 且 projectName == project
      2) exact：name == dsName
      3) contains：name contains dsName
      4) 若仍未命中且 dsName 含括号/空格：去掉括号内容后重试 exact / contains
    """
    if not isinstance(datasource_name, str) or not datasource_name.strip():
        return None

    raw = datasource_name.strip()

    # 名称规范化：提取项目（若存在" | 项目 : xxx"），并保留左侧真实名称
    project: Optional[str] = None
    name = raw
    splitter = " | 项目 : "
    if splitter in raw:
        parts = raw.split(splitter, 1)
        name = parts[0].strip()
        project = (parts[1] or "").strip() or None

    # 辅助：去掉括号中的描述（如 "销售分析(IMPALA)" → "销售分析"）
    import re
    def strip_parentheses(s: str) -> str:
        return re.sub(r"\s*\([^)]*\)\s*", " ", s).strip()

    # 查询1：exact + project
    if project:
        q = """
        query($name:String!, $project:String!) {
          publishedDatasources(filter:{ name:$name, projectName:$project }) {
            id luid name projectName updatedAt owner{username}
          }
        }
        """
        try:
            data = _graphql_post(domain, api_key, q, {"name": name, "project": project}, site=site)
            items = data.get("data", {}).get("publishedDatasources") or []
            for it in items:
                if (it.get("name") or "").strip() == name and (it.get("projectName") or "").strip() == project:
                    return it.get("luid")
        except Exception:
            pass

    # 查询2：exact
    q_exact = """
    query($name:String!) {
      publishedDatasources(filter:{ name:$name }) {
        id luid name projectName updatedAt owner{username}
      }
    }
    """
    try:
        data = _graphql_post(domain, api_key, q_exact, {"name": name}, site=site)
        items = data.get("data", {}).get("publishedDatasources") or []
        for it in items:
            if (it.get("name") or "").strip() == name:
                return it.get("luid")
        if items:
            # 兜底返回第一个
            return items[0].get("luid")
    except Exception:
        pass

    # 查询3：contains
    q_contains = """
    query($kw:String!) {
      publishedDatasources(filter:{ name:{ contains:$kw } }) {
        id luid name projectName updatedAt owner{username}
      }
    }
    """
    try:
        data = _graphql_post(domain, api_key, q_contains, {"kw": name}, site=site)
        items = data.get("data", {}).get("publishedDatasources") or []
        if items:
            for it in items:
                if (it.get("name") or "").strip() == name:
                    return it.get("luid")
            return items[0].get("luid")
    except Exception:
        pass

    # 查询4：去括号后重试
    name2 = strip_parentheses(name)
    if name2 and name2 != name:
        try:
            data = _graphql_post(domain, api_key, q_exact, {"name": name2}, site=site)
            items = data.get("data", {}).get("publishedDatasources") or []
            for it in items:
                if (it.get("name") or "").strip() == name2:
                    return it.get("luid")
            if not items:
                data = _graphql_post(domain, api_key, q_contains, {"kw": name2}, site=site)
                items = data.get("data", {}).get("publishedDatasources") or []
                if items:
                    for it in items:
                        if (it.get("name") or "").strip() == name2:
                            return it.get("luid")
                    return items[0].get("luid")
        except Exception:
            pass

    return None


def get_data_dictionary_by_name(api_key: str, domain: str, datasource_name: str, site: Optional[str] = None) -> Dict[str, Any]:
    """
    便捷入口：通过数据源名称解析 LUID，然后获取字段元数据。
    支持传入 site：会在请求头附带 X-Tableau-Site。
    """
    luid = get_datasource_luid_by_name(api_key=api_key, domain=domain, datasource_name=datasource_name, site=site)
    if not luid:
        raise RuntimeError(f"Datasource not found by name: {datasource_name}")
    return get_data_dictionary(api_key=api_key, domain=domain, datasource_luid=luid, site=site)

# 统一：基于数据源名称构建维度/度量清单（从字段字典中归类）
def _build_metadata_from_name(api_key: str, domain: str, datasource_name: str, site: Optional[str] = None) -> Dict[str, List[str]]:
    """
    使用 get_data_dictionary_by_name 获取字段字典，并按 dataType 将字段划分为 dimensions / measures：
    - INTEGER / REAL 归为 measures
    - 其他类型归为 dimensions
    返回：{"dimensions": [...], "measures": [...], "fields": [...]}
    """
    dd = get_data_dictionary_by_name(api_key=api_key, domain=domain, datasource_name=datasource_name, site=site)
    fields = dd.get("fields", []) or []

    dims: List[str] = []
    meas: List[str] = []

    for f in fields:
        name = f.get("name")
        dt = f.get("dataType")
        if not isinstance(name, str) or not name.strip():
            continue
        if str(dt) in ("INTEGER", "REAL"):
            meas.append(name.strip())
        else:
            dims.append(name.strip())

    return {
        "dimensions": dims,
        "measures": meas,
        "fields": fields  # 添加完整的fields信息
    }
