# -*- coding: utf-8 -*-
"""
InsightAgent Internal State Definition

Defines InsightState for the InsightAgent Subgraph internal use.
This state extends VizQLState with InsightAgent-specific fields.

Architecture (Pyramid Structure):
- VizQLState (orchestration): Workflow state with all node outputs
- InsightState (agent): Extends VizQLState with Subgraph internal fields:
  - enhanced_profile: Dict (EnhancedDataProfile.model_dump())
  - chunks: List[Dict] (PriorityChunk.model_dump() list)
  - director_decision: Dict (DirectorDecision.model_dump())
  - analyst_output: Dict (AnalystOutputWithHistory.model_dump())
  - iteration_count: int (current iteration)
  - should_continue: bool (whether to continue analysis)

⚠️ State 序列化原则（支持 checkpoint/持久化/回放）：
- State 中只存可 JSON 化的基本类型或结构
- 复杂对象（如 Pydantic BaseModel）在存入 State 前必须调用 .model_dump()
- 从 State 读取后需要重新构造对象（使用 Model.model_validate(dict)）

Why inherit from VizQLState?
- Subgraph nodes can directly access main workflow fields (query_result, etc.)
- Subgraph nodes can directly write to main workflow fields (insights, etc.)
- Consistent with SemanticParserState design
- No manual input/output mapping needed in insight_node
"""
from typing import Any, Dict, List, Optional

# Import from orchestration layer (correct dependency direction)
from tableau_assistant.src.orchestration.workflow.state import VizQLState

# 注意：以下导入已移除，State 中不再直接存储 Pydantic 对象
# - EnhancedDataProfile, PriorityChunk, DirectorDecision, DirectorAction, AnalystOutputWithHistory
# 这些对象在写入 State 前必须调用 .model_dump() 转为 dict
# 从 State 读取后需要重新构造对象（使用 Model.model_validate(dict)）


class InsightState(VizQLState):
    """
    InsightAgent Subgraph internal state.
    
    Extends VizQLState with Subgraph intermediate outputs:
    - enhanced_profile: Dict (EnhancedDataProfile.model_dump())
    - chunks: List[Dict] (PriorityChunk.model_dump() list)
    - director_decision: Dict (DirectorDecision.model_dump())
    - current_action: str (DirectorAction.value)
    - current_target: Dict (target chunk/dimension/anomaly)
    - analyzed_chunk_ids: List[int] (IDs of analyzed chunks)
    - analyst_output: Dict (AnalystOutputWithHistory.model_dump())
    - iteration_count: int (current iteration)
    - should_continue: bool (whether to continue analysis)
    - final_summary: str (generated by Director when stopping)
    
    ⚠️ State 序列化：所有复杂对象存储为 dict，非 Pydantic 对象
    
    Used by:
    - profiler_node: Writes enhanced_profile, chunks
    - director_node: Reads profile/chunks/insights, writes director_decision
    - analyzer_node: Reads decision, writes analyst_output
    - InsightAgent Subgraph: Uses full InsightState
    
    Note:
    - VizQLState contains query_result (input) and insights (output)
    - These fields are for internal Subgraph communication only
    - Main workflow sees insights via VizQLState.insights
    """
    
    # ═══════════════════════════════════════════════════════════════════════════
    # Phase 1: Profiler Output
    # ⚠️ State 序列化：存储为 dict（.model_dump()），非 Pydantic 对象
    # ═══════════════════════════════════════════════════════════════════════════
    
    # Enhanced data profile with Tableau Pulse-style insights
    enhanced_profile: Optional[Dict[str, Any]]  # EnhancedDataProfile.model_dump()
    
    # Data insight profile for chunking and analysis (from StatisticalAnalyzer)
    insight_profile: Optional[Any]  # DataInsightProfile
    
    # Data chunks created by profiler based on recommended strategy
    chunks: Optional[List[Dict[str, Any]]]  # [PriorityChunk.model_dump(), ...]
    
    # ═══════════════════════════════════════════════════════════════════════════
    # Phase 2: Director State
    # ⚠️ State 序列化：存储为 dict（.model_dump()），非 Pydantic 对象
    # ═══════════════════════════════════════════════════════════════════════════
    
    # Current director decision
    director_decision: Optional[Dict[str, Any]]  # DirectorDecision.model_dump()
    
    # Current action to execute (存储为字符串值)
    current_action: Optional[str]  # DirectorAction.value
    
    # Target chunk/dimension/anomaly for current action
    current_target: Optional[Dict[str, Any]]
    
    # ═══════════════════════════════════════════════════════════════════════════
    # Phase 3: Analyzer State
    # ⚠️ State 序列化：存储为 dict（.model_dump()），非 Pydantic 对象
    # ═══════════════════════════════════════════════════════════════════════════
    
    # IDs of chunks that have been analyzed
    analyzed_chunk_ids: Optional[List[int]]
    
    # Latest analyst output (new insights + history processing suggestions)
    analyst_output: Optional[Dict[str, Any]]  # AnalystOutputWithHistory.model_dump()
    
    # ═══════════════════════════════════════════════════════════════════════════
    # Control Fields
    # ═══════════════════════════════════════════════════════════════════════════
    
    # Current iteration count
    iteration_count: Optional[int]
    
    # Whether to continue analysis (set by Director)
    should_continue: Optional[bool]
    
    # Maximum iterations allowed
    max_iterations: Optional[int]
    
    # Final summary (generated by Director when should_continue=False)
    final_summary: Optional[str]
    
    # Error message if analysis fails
    error_message: Optional[str]


__all__ = ["InsightState"]
