# -*- coding: utf-8 -*-
"""
InsightAgent Internal State Definition

Defines InsightState for the InsightAgent Subgraph internal use.
This state extends VizQLState with InsightAgent-specific fields.

Architecture (Pyramid Structure):
- VizQLState (orchestration): Workflow state with all node outputs
- InsightState (agent): Extends VizQLState with Subgraph internal fields:
  - enhanced_profile: EnhancedDataProfile (Tableau Pulse-style analysis)
  - chunks: List[PriorityChunk] (data chunks for progressive analysis)
  - director_decision: DirectorDecision (current decision)
  - analyst_output: AnalystOutputWithHistory (latest analyst output)
  - iteration_count: int (current iteration)
  - should_continue: bool (whether to continue analysis)

Why inherit from VizQLState?
- Subgraph nodes can directly access main workflow fields (query_result, etc.)
- Subgraph nodes can directly write to main workflow fields (insights, etc.)
- Consistent with SemanticParserState design
- No manual input/output mapping needed in insight_node
"""
from typing import Any, Dict, List, Optional

# Import from orchestration layer (correct dependency direction)
from tableau_assistant.src.orchestration.workflow.state import VizQLState
from tableau_assistant.src.agents.insight.models import (
    # Profile models
    EnhancedDataProfile,
    # Chunk models
    PriorityChunk,
    # Director models
    DirectorDecision,
    DirectorAction,
    # Analyst models
    AnalystOutputWithHistory,
)


class InsightState(VizQLState):
    """
    InsightAgent Subgraph internal state.
    
    Extends VizQLState with Subgraph intermediate outputs:
    - enhanced_profile: EnhancedDataProfile (Tableau Pulse-style analysis)
    - chunks: List[PriorityChunk] (data chunks for progressive analysis)
    - director_decision: DirectorDecision (current decision)
    - current_action: DirectorAction (current action to execute)
    - current_target: Dict (target chunk/dimension/anomaly)
    - analyzed_chunk_ids: List[int] (IDs of analyzed chunks)
    - analyst_output: AnalystOutputWithHistory (latest analyst output)
    - iteration_count: int (current iteration)
    - should_continue: bool (whether to continue analysis)
    - final_summary: str (generated by Director when stopping)
    
    Used by:
    - profiler_node: Writes enhanced_profile, chunks
    - director_node: Reads profile/chunks/insights, writes director_decision
    - analyzer_node: Reads decision, writes analyst_output
    - InsightAgent Subgraph: Uses full InsightState
    
    Note:
    - VizQLState contains query_result (input) and insights (output)
    - These fields are for internal Subgraph communication only
    - Main workflow sees insights via VizQLState.insights
    """
    
    # ═══════════════════════════════════════════════════════════════════════════
    # Phase 1: Profiler Output
    # ═══════════════════════════════════════════════════════════════════════════
    
    # Enhanced data profile with Tableau Pulse-style insights
    enhanced_profile: Optional[EnhancedDataProfile]
    
    # Data chunks created by profiler based on recommended strategy
    chunks: Optional[List[PriorityChunk]]
    
    # ═══════════════════════════════════════════════════════════════════════════
    # Phase 2: Director State
    # ═══════════════════════════════════════════════════════════════════════════
    
    # Current director decision
    director_decision: Optional[DirectorDecision]
    
    # Current action to execute
    current_action: Optional[DirectorAction]
    
    # Target chunk/dimension/anomaly for current action
    current_target: Optional[Dict[str, Any]]
    
    # ═══════════════════════════════════════════════════════════════════════════
    # Phase 3: Analyzer State
    # ═══════════════════════════════════════════════════════════════════════════
    
    # IDs of chunks that have been analyzed
    analyzed_chunk_ids: Optional[List[int]]
    
    # Latest analyst output (new insights + history processing suggestions)
    analyst_output: Optional[AnalystOutputWithHistory]
    
    # ═══════════════════════════════════════════════════════════════════════════
    # Control Fields
    # ═══════════════════════════════════════════════════════════════════════════
    
    # Current iteration count
    iteration_count: Optional[int]
    
    # Whether to continue analysis (set by Director)
    should_continue: Optional[bool]
    
    # Maximum iterations allowed
    max_iterations: Optional[int]
    
    # Final summary (generated by Director when should_continue=False)
    final_summary: Optional[str]
    
    # Error message if analysis fails
    error_message: Optional[str]


__all__ = ["InsightState"]
